// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module design_1_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_708_18 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        img_dout,
        img_empty_n,
        img_read,
        pix_val_V_55,
        pix_val_V_54,
        pix_val_V_53,
        pix_val_V_52,
        pix_val_V_51,
        pix_val_V_50,
        trunc_ln5,
        cmp388_2,
        cmp388_1,
        cmp388,
        icmp_ln698,
        cmp355_6,
        cmp355_5,
        cmp355_4,
        cmp355_3,
        cmp355_2,
        cmp355_1,
        sub353,
        cmp355,
        bytePlanes_01_din,
        bytePlanes_01_full_n,
        bytePlanes_01_write,
        pix_val_V_63_out,
        pix_val_V_63_out_ap_vld,
        pix_val_V_62_out,
        pix_val_V_62_out_ap_vld,
        pix_val_V_61_out,
        pix_val_V_61_out_ap_vld,
        pix_val_V_60_out,
        pix_val_V_60_out_ap_vld,
        pix_val_V_59_out,
        pix_val_V_59_out_ap_vld,
        pix_val_V_58_out,
        pix_val_V_58_out_ap_vld,
        out_pix_V_23_out,
        out_pix_V_23_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 8'd1;
parameter    ap_ST_fsm_pp0_stage1 = 8'd2;
parameter    ap_ST_fsm_pp0_stage2 = 8'd4;
parameter    ap_ST_fsm_pp0_stage3 = 8'd8;
parameter    ap_ST_fsm_pp0_stage4 = 8'd16;
parameter    ap_ST_fsm_pp0_stage5 = 8'd32;
parameter    ap_ST_fsm_pp0_stage6 = 8'd64;
parameter    ap_ST_fsm_pp0_stage7 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [47:0] img_dout;
input   img_empty_n;
output   img_read;
input  [7:0] pix_val_V_55;
input  [7:0] pix_val_V_54;
input  [7:0] pix_val_V_53;
input  [7:0] pix_val_V_52;
input  [7:0] pix_val_V_51;
input  [7:0] pix_val_V_50;
input  [9:0] trunc_ln5;
input  [0:0] cmp388_2;
input  [0:0] cmp388_1;
input  [0:0] cmp388;
input  [0:0] icmp_ln698;
input  [0:0] cmp355_6;
input  [0:0] cmp355_5;
input  [0:0] cmp355_4;
input  [0:0] cmp355_3;
input  [0:0] cmp355_2;
input  [0:0] cmp355_1;
input  [10:0] sub353;
input  [0:0] cmp355;
output  [127:0] bytePlanes_01_din;
input   bytePlanes_01_full_n;
output   bytePlanes_01_write;
output  [7:0] pix_val_V_63_out;
output   pix_val_V_63_out_ap_vld;
output  [7:0] pix_val_V_62_out;
output   pix_val_V_62_out_ap_vld;
output  [7:0] pix_val_V_61_out;
output   pix_val_V_61_out_ap_vld;
output  [7:0] pix_val_V_60_out;
output   pix_val_V_60_out_ap_vld;
output  [7:0] pix_val_V_59_out;
output   pix_val_V_59_out_ap_vld;
output  [7:0] pix_val_V_58_out;
output   pix_val_V_58_out_ap_vld;
output  [383:0] out_pix_V_23_out;
output   out_pix_V_23_out_ap_vld;

reg ap_idle;
reg img_read;
reg[127:0] bytePlanes_01_din;
reg bytePlanes_01_write;
reg pix_val_V_63_out_ap_vld;
reg pix_val_V_62_out_ap_vld;
reg pix_val_V_61_out_ap_vld;
reg pix_val_V_60_out_ap_vld;
reg pix_val_V_59_out_ap_vld;
reg pix_val_V_58_out_ap_vld;
reg out_pix_V_23_out_ap_vld;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage2;
reg   [0:0] icmp_ln708_reg_1472;
reg   [0:0] or_ln713_1_reg_1508;
reg    ap_predicate_op83_read_state3;
reg    ap_block_state3_pp0_stage2_iter0;
reg    ap_block_pp0_stage2_subdone;
reg    ap_condition_exit_pp0_iter0_stage2;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_pp0_stage7;
reg   [0:0] or_ln713_6_reg_1573;
reg    ap_predicate_op167_read_state8;
reg    ap_block_state8_pp0_stage7_iter0;
reg    ap_block_pp0_stage7_subdone;
reg    img_blk_n;
wire    ap_block_pp0_stage0;
reg   [0:0] or_ln713_7_reg_1577;
wire    ap_block_pp0_stage7;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_pp0_stage6;
reg   [0:0] or_ln713_5_reg_1569;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_pp0_stage5;
reg   [0:0] or_ln713_4_reg_1565;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_pp0_stage4;
reg   [0:0] or_ln713_3_reg_1556;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3;
reg   [0:0] or_ln713_2_reg_1547;
wire    ap_block_pp0_stage2;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1;
reg   [0:0] or_ln713_reg_1487;
reg    bytePlanes_01_blk_n;
reg   [0:0] or_ln725_reg_1491;
reg   [0:0] or_ln725_1_reg_1495;
reg   [0:0] or_ln725_2_reg_1499;
reg   [0:0] or_ln725_2_reg_1499_pp0_iter1_reg;
reg   [7:0] pix_val_V_62_reg_283;
reg   [7:0] pix_val_V_61_reg_293;
reg   [7:0] pix_val_V_60_reg_303;
reg   [7:0] pix_val_V_59_reg_313;
reg   [7:0] pix_val_V_58_reg_323;
reg   [7:0] pix_val_V_57_reg_333;
reg   [7:0] pix_val_V_70_reg_343;
reg   [7:0] pix_val_V_69_reg_354;
reg   [7:0] pix_val_V_68_reg_365;
reg   [7:0] pix_val_V_67_reg_376;
reg   [7:0] pix_val_V_66_reg_387;
reg   [7:0] pix_val_V_65_reg_398;
reg   [7:0] pix_val_V_78_reg_409;
reg   [7:0] pix_val_V_77_reg_420;
reg   [7:0] pix_val_V_76_reg_431;
reg   [7:0] pix_val_V_75_reg_442;
reg   [7:0] pix_val_V_74_reg_453;
reg   [7:0] pix_val_V_73_reg_464;
reg   [7:0] pix_val_V_86_reg_475;
reg   [7:0] pix_val_V_85_reg_486;
reg   [7:0] pix_val_V_84_reg_497;
reg   [7:0] pix_val_V_83_reg_508;
reg   [7:0] pix_val_V_82_reg_519;
reg   [7:0] pix_val_V_81_reg_530;
reg   [7:0] pix_val_V_94_reg_541;
reg   [7:0] pix_val_V_93_reg_552;
reg   [7:0] pix_val_V_92_reg_563;
reg   [7:0] pix_val_V_91_reg_574;
reg   [7:0] pix_val_V_90_reg_585;
reg   [7:0] pix_val_V_89_reg_596;
reg   [7:0] pix_val_V_102_reg_607;
reg   [7:0] pix_val_V_101_reg_618;
reg   [7:0] pix_val_V_100_reg_629;
reg   [7:0] pix_val_V_99_reg_640;
reg   [7:0] pix_val_V_98_reg_651;
reg   [7:0] pix_val_V_97_reg_662;
reg    ap_predicate_op64_read_state2;
reg    ap_block_state2_pp0_stage1_iter0;
reg    ap_block_state10_pp0_stage1_iter1;
reg    ap_block_pp0_stage1_11001;
reg    ap_predicate_op115_read_state5;
reg    ap_block_state5_pp0_stage4_iter0;
reg    ap_block_pp0_stage4_11001;
reg    ap_block_pp0_stage2_11001;
reg    ap_predicate_op134_read_state6;
reg    ap_predicate_op143_write_state6;
reg    ap_block_state6_pp0_stage5_iter0;
reg    ap_block_pp0_stage5_11001;
wire    ap_block_state1_pp0_stage0_iter0;
reg    ap_predicate_op182_read_state9;
reg    ap_block_state9_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
reg    ap_predicate_op99_read_state4;
reg    ap_block_state4_pp0_stage3_iter0;
reg    ap_block_pp0_stage3_11001;
reg    ap_predicate_op152_read_state7;
reg    ap_block_state7_pp0_stage6_iter0;
reg    ap_block_pp0_stage6_11001;
wire   [0:0] icmp_ln708_fu_976_p2;
reg   [0:0] icmp_ln708_reg_1472_pp0_iter1_reg;
wire   [0:0] cmp354_fu_992_p2;
reg   [0:0] cmp354_reg_1476;
wire   [0:0] or_ln713_fu_998_p2;
wire   [0:0] or_ln725_fu_1004_p2;
wire   [0:0] or_ln725_1_fu_1010_p2;
wire   [0:0] or_ln725_2_fu_1016_p2;
wire   [7:0] pix_val_V_49_fu_1027_p1;
wire   [0:0] or_ln713_1_fu_1031_p2;
wire   [7:0] pix_val_V_63_fu_1053_p1;
wire   [0:0] or_ln713_2_fu_1057_p2;
wire   [7:0] pix_val_V_71_fu_1061_p1;
wire   [0:0] or_ln713_3_fu_1065_p2;
wire   [7:0] pix_val_V_79_fu_1069_p1;
wire   [0:0] or_ln713_4_fu_1073_p2;
wire   [0:0] or_ln713_5_fu_1077_p2;
wire   [0:0] or_ln713_6_fu_1081_p2;
wire   [0:0] or_ln713_7_fu_1085_p2;
wire   [7:0] pix_val_V_87_fu_1089_p1;
wire   [7:0] pix_val_V_95_fu_1130_p1;
wire   [7:0] pix_val_V_103_fu_1134_p1;
reg    ap_block_pp0_stage7_11001;
wire   [7:0] pix_val_V_111_fu_1138_p1;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_block_pp0_stage1_subdone;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_62_reg_283;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_61_reg_293;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_60_reg_303;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_59_reg_313;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_58_reg_323;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_57_reg_333;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_70_reg_343;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_69_reg_354;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_68_reg_365;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_67_reg_376;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_66_reg_387;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_65_reg_398;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_78_reg_409;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_77_reg_420;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_76_reg_431;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_75_reg_442;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_74_reg_453;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_73_reg_464;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_86_reg_475;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_85_reg_486;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_84_reg_497;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_83_reg_508;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_82_reg_519;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_81_reg_530;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_94_reg_541;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_93_reg_552;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_92_reg_563;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_91_reg_574;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_90_reg_585;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_89_reg_596;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_102_reg_607;
reg   [7:0] ap_phi_reg_pp0_iter1_pix_val_V_102_reg_607;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_101_reg_618;
reg   [7:0] ap_phi_reg_pp0_iter1_pix_val_V_101_reg_618;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_100_reg_629;
reg   [7:0] ap_phi_reg_pp0_iter1_pix_val_V_100_reg_629;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_99_reg_640;
reg   [7:0] ap_phi_reg_pp0_iter1_pix_val_V_99_reg_640;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_98_reg_651;
reg   [7:0] ap_phi_reg_pp0_iter1_pix_val_V_98_reg_651;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_97_reg_662;
reg   [7:0] ap_phi_reg_pp0_iter1_pix_val_V_97_reg_662;
wire   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_110_reg_673;
reg   [7:0] ap_phi_reg_pp0_iter1_pix_val_V_110_reg_673;
wire   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_109_reg_683;
reg   [7:0] ap_phi_reg_pp0_iter1_pix_val_V_109_reg_683;
wire   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_108_reg_693;
reg   [7:0] ap_phi_reg_pp0_iter1_pix_val_V_108_reg_693;
wire   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_107_reg_703;
reg   [7:0] ap_phi_reg_pp0_iter1_pix_val_V_107_reg_703;
wire   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_106_reg_713;
reg   [7:0] ap_phi_reg_pp0_iter1_pix_val_V_106_reg_713;
wire   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_105_reg_723;
reg   [7:0] ap_phi_reg_pp0_iter1_pix_val_V_105_reg_723;
reg   [7:0] ap_phi_mux_pix_val_V_118_phi_fu_736_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_118_reg_733;
reg   [7:0] ap_phi_reg_pp0_iter1_pix_val_V_118_reg_733;
reg   [7:0] ap_phi_mux_pix_val_V_117_phi_fu_746_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_117_reg_743;
reg   [7:0] ap_phi_reg_pp0_iter1_pix_val_V_117_reg_743;
reg   [7:0] ap_phi_mux_pix_val_V_116_phi_fu_756_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_116_reg_753;
reg   [7:0] ap_phi_reg_pp0_iter1_pix_val_V_116_reg_753;
reg   [7:0] ap_phi_mux_pix_val_V_115_phi_fu_766_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_115_reg_763;
reg   [7:0] ap_phi_reg_pp0_iter1_pix_val_V_115_reg_763;
reg   [7:0] ap_phi_mux_pix_val_V_114_phi_fu_776_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_114_reg_773;
reg   [7:0] ap_phi_reg_pp0_iter1_pix_val_V_114_reg_773;
reg   [7:0] ap_phi_mux_pix_val_V_113_phi_fu_786_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_113_reg_783;
reg   [7:0] ap_phi_reg_pp0_iter1_pix_val_V_113_reg_783;
reg   [9:0] x_fu_128;
wire   [9:0] x_4_fu_982_p2;
wire    ap_loop_init;
reg   [9:0] ap_sig_allocacmp_x_3;
reg   [7:0] pix_val_V_fu_132;
reg   [7:0] pix_val_V_38_fu_136;
reg   [7:0] pix_val_V_39_fu_140;
reg   [7:0] pix_val_V_40_fu_144;
reg   [7:0] pix_val_V_41_fu_148;
reg   [7:0] pix_val_V_42_fu_152;
wire   [127:0] p_s_fu_1093_p17;
reg    ap_block_pp0_stage5_01001;
wire   [127:0] p_1_fu_1142_p17;
reg    ap_block_pp0_stage0_01001;
wire   [127:0] p_0_fu_1279_p17;
reg    ap_block_pp0_stage1_01001;
wire   [10:0] zext_ln708_fu_988_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [7:0] ap_NS_fsm;
reg    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to1;
reg    ap_block_pp0_stage3_subdone;
reg    ap_block_pp0_stage4_subdone;
reg    ap_block_pp0_stage5_subdone;
reg    ap_block_pp0_stage6_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_1133;
reg    ap_condition_1137;
reg    ap_condition_1141;
reg    ap_condition_1145;
reg    ap_condition_1148;
reg    ap_condition_1151;
reg    ap_condition_1154;
reg    ap_condition_1157;
reg    ap_condition_1160;
reg    ap_condition_1163;
reg    ap_condition_540;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

design_1_v_frmbuf_wr_0_0_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage2),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage2)) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage7_subdone) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln708_reg_1472 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1137)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_57_reg_333 <= pix_val_V_fu_132;
        end else if ((1'b1 == ap_condition_1133)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_57_reg_333 <= pix_val_V_49_fu_1027_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln708_reg_1472 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1137)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_58_reg_323 <= pix_val_V_38_fu_136;
        end else if ((1'b1 == ap_condition_1133)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_58_reg_323 <= {{img_dout[15:8]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln708_reg_1472 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1137)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_59_reg_313 <= pix_val_V_39_fu_140;
        end else if ((1'b1 == ap_condition_1133)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_59_reg_313 <= {{img_dout[23:16]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln708_reg_1472 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1137)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_60_reg_303 <= pix_val_V_40_fu_144;
        end else if ((1'b1 == ap_condition_1133)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_60_reg_303 <= {{img_dout[31:24]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln708_reg_1472 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1137)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_61_reg_293 <= pix_val_V_41_fu_148;
        end else if ((1'b1 == ap_condition_1133)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_61_reg_293 <= {{img_dout[39:32]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln708_reg_1472 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1137)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_62_reg_283 <= pix_val_V_42_fu_152;
        end else if ((1'b1 == ap_condition_1133)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_62_reg_283 <= {{img_dout[47:40]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln708_reg_1472 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1145)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_65_reg_398 <= ap_phi_reg_pp0_iter0_pix_val_V_57_reg_333;
        end else if ((1'b1 == ap_condition_1141)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_65_reg_398 <= pix_val_V_63_fu_1053_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln708_reg_1472 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1145)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_66_reg_387 <= ap_phi_reg_pp0_iter0_pix_val_V_58_reg_323;
        end else if ((1'b1 == ap_condition_1141)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_66_reg_387 <= {{img_dout[15:8]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln708_reg_1472 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1145)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_67_reg_376 <= ap_phi_reg_pp0_iter0_pix_val_V_59_reg_313;
        end else if ((1'b1 == ap_condition_1141)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_67_reg_376 <= {{img_dout[23:16]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln708_reg_1472 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1145)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_68_reg_365 <= ap_phi_reg_pp0_iter0_pix_val_V_60_reg_303;
        end else if ((1'b1 == ap_condition_1141)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_68_reg_365 <= {{img_dout[31:24]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln708_reg_1472 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1145)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_69_reg_354 <= ap_phi_reg_pp0_iter0_pix_val_V_61_reg_293;
        end else if ((1'b1 == ap_condition_1141)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_69_reg_354 <= {{img_dout[39:32]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln708_reg_1472 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1145)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_70_reg_343 <= ap_phi_reg_pp0_iter0_pix_val_V_62_reg_283;
        end else if ((1'b1 == ap_condition_1141)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_70_reg_343 <= {{img_dout[47:40]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln708_reg_1472 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1151)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_73_reg_464 <= ap_phi_reg_pp0_iter0_pix_val_V_65_reg_398;
        end else if ((1'b1 == ap_condition_1148)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_73_reg_464 <= pix_val_V_71_fu_1061_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln708_reg_1472 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1151)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_74_reg_453 <= ap_phi_reg_pp0_iter0_pix_val_V_66_reg_387;
        end else if ((1'b1 == ap_condition_1148)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_74_reg_453 <= {{img_dout[15:8]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln708_reg_1472 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1151)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_75_reg_442 <= ap_phi_reg_pp0_iter0_pix_val_V_67_reg_376;
        end else if ((1'b1 == ap_condition_1148)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_75_reg_442 <= {{img_dout[23:16]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln708_reg_1472 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1151)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_76_reg_431 <= ap_phi_reg_pp0_iter0_pix_val_V_68_reg_365;
        end else if ((1'b1 == ap_condition_1148)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_76_reg_431 <= {{img_dout[31:24]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln708_reg_1472 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1151)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_77_reg_420 <= ap_phi_reg_pp0_iter0_pix_val_V_69_reg_354;
        end else if ((1'b1 == ap_condition_1148)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_77_reg_420 <= {{img_dout[39:32]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln708_reg_1472 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1151)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_78_reg_409 <= ap_phi_reg_pp0_iter0_pix_val_V_70_reg_343;
        end else if ((1'b1 == ap_condition_1148)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_78_reg_409 <= {{img_dout[47:40]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln708_reg_1472 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1157)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_81_reg_530 <= ap_phi_reg_pp0_iter0_pix_val_V_73_reg_464;
        end else if ((1'b1 == ap_condition_1154)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_81_reg_530 <= pix_val_V_79_fu_1069_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln708_reg_1472 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1157)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_82_reg_519 <= ap_phi_reg_pp0_iter0_pix_val_V_74_reg_453;
        end else if ((1'b1 == ap_condition_1154)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_82_reg_519 <= {{img_dout[15:8]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln708_reg_1472 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1157)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_83_reg_508 <= ap_phi_reg_pp0_iter0_pix_val_V_75_reg_442;
        end else if ((1'b1 == ap_condition_1154)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_83_reg_508 <= {{img_dout[23:16]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln708_reg_1472 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1157)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_84_reg_497 <= ap_phi_reg_pp0_iter0_pix_val_V_76_reg_431;
        end else if ((1'b1 == ap_condition_1154)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_84_reg_497 <= {{img_dout[31:24]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln708_reg_1472 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1157)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_85_reg_486 <= ap_phi_reg_pp0_iter0_pix_val_V_77_reg_420;
        end else if ((1'b1 == ap_condition_1154)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_85_reg_486 <= {{img_dout[39:32]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln708_reg_1472 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1157)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_86_reg_475 <= ap_phi_reg_pp0_iter0_pix_val_V_78_reg_409;
        end else if ((1'b1 == ap_condition_1154)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_86_reg_475 <= {{img_dout[47:40]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln708_reg_1472 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1163)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_89_reg_596 <= ap_phi_reg_pp0_iter0_pix_val_V_81_reg_530;
        end else if ((1'b1 == ap_condition_1160)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_89_reg_596 <= pix_val_V_87_fu_1089_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln708_reg_1472 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1163)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_90_reg_585 <= ap_phi_reg_pp0_iter0_pix_val_V_82_reg_519;
        end else if ((1'b1 == ap_condition_1160)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_90_reg_585 <= {{img_dout[15:8]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln708_reg_1472 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1163)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_91_reg_574 <= ap_phi_reg_pp0_iter0_pix_val_V_83_reg_508;
        end else if ((1'b1 == ap_condition_1160)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_91_reg_574 <= {{img_dout[23:16]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln708_reg_1472 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1163)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_92_reg_563 <= ap_phi_reg_pp0_iter0_pix_val_V_84_reg_497;
        end else if ((1'b1 == ap_condition_1160)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_92_reg_563 <= {{img_dout[31:24]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln708_reg_1472 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1163)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_93_reg_552 <= ap_phi_reg_pp0_iter0_pix_val_V_85_reg_486;
        end else if ((1'b1 == ap_condition_1160)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_93_reg_552 <= {{img_dout[39:32]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln708_reg_1472 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_1163)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_94_reg_541 <= ap_phi_reg_pp0_iter0_pix_val_V_86_reg_475;
        end else if ((1'b1 == ap_condition_1160)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_94_reg_541 <= {{img_dout[47:40]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_540)) begin
        if (((icmp_ln708_reg_1472 == 1'd0) & (or_ln713_5_reg_1569 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_pix_val_V_100_reg_629 <= ap_phi_reg_pp0_iter0_pix_val_V_92_reg_563;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_pix_val_V_100_reg_629 <= ap_phi_reg_pp0_iter0_pix_val_V_100_reg_629;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_540)) begin
        if (((icmp_ln708_reg_1472 == 1'd0) & (or_ln713_5_reg_1569 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_pix_val_V_101_reg_618 <= ap_phi_reg_pp0_iter0_pix_val_V_93_reg_552;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_pix_val_V_101_reg_618 <= ap_phi_reg_pp0_iter0_pix_val_V_101_reg_618;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_540)) begin
        if (((icmp_ln708_reg_1472 == 1'd0) & (or_ln713_5_reg_1569 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_pix_val_V_102_reg_607 <= ap_phi_reg_pp0_iter0_pix_val_V_94_reg_541;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_pix_val_V_102_reg_607 <= ap_phi_reg_pp0_iter0_pix_val_V_102_reg_607;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((or_ln713_6_reg_1573 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln708_reg_1472 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_pix_val_V_105_reg_723 <= ap_phi_reg_pp0_iter1_pix_val_V_97_reg_662;
    end else if (((or_ln713_6_reg_1573 == 1'd1) & (1'b0 == ap_block_pp0_stage7_11001) & (icmp_ln708_reg_1472 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter1_pix_val_V_105_reg_723 <= pix_val_V_103_fu_1134_p1;
    end else if (((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter1_pix_val_V_105_reg_723 <= ap_phi_reg_pp0_iter0_pix_val_V_105_reg_723;
    end
end

always @ (posedge ap_clk) begin
    if (((or_ln713_6_reg_1573 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln708_reg_1472 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_pix_val_V_106_reg_713 <= ap_phi_reg_pp0_iter1_pix_val_V_98_reg_651;
    end else if (((or_ln713_6_reg_1573 == 1'd1) & (1'b0 == ap_block_pp0_stage7_11001) & (icmp_ln708_reg_1472 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter1_pix_val_V_106_reg_713 <= {{img_dout[15:8]}};
    end else if (((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter1_pix_val_V_106_reg_713 <= ap_phi_reg_pp0_iter0_pix_val_V_106_reg_713;
    end
end

always @ (posedge ap_clk) begin
    if (((or_ln713_6_reg_1573 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln708_reg_1472 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_pix_val_V_107_reg_703 <= ap_phi_reg_pp0_iter1_pix_val_V_99_reg_640;
    end else if (((or_ln713_6_reg_1573 == 1'd1) & (1'b0 == ap_block_pp0_stage7_11001) & (icmp_ln708_reg_1472 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter1_pix_val_V_107_reg_703 <= {{img_dout[23:16]}};
    end else if (((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter1_pix_val_V_107_reg_703 <= ap_phi_reg_pp0_iter0_pix_val_V_107_reg_703;
    end
end

always @ (posedge ap_clk) begin
    if (((or_ln713_6_reg_1573 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln708_reg_1472 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_pix_val_V_108_reg_693 <= ap_phi_reg_pp0_iter1_pix_val_V_100_reg_629;
    end else if (((or_ln713_6_reg_1573 == 1'd1) & (1'b0 == ap_block_pp0_stage7_11001) & (icmp_ln708_reg_1472 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter1_pix_val_V_108_reg_693 <= {{img_dout[31:24]}};
    end else if (((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter1_pix_val_V_108_reg_693 <= ap_phi_reg_pp0_iter0_pix_val_V_108_reg_693;
    end
end

always @ (posedge ap_clk) begin
    if (((or_ln713_6_reg_1573 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln708_reg_1472 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_pix_val_V_109_reg_683 <= ap_phi_reg_pp0_iter1_pix_val_V_101_reg_618;
    end else if (((or_ln713_6_reg_1573 == 1'd1) & (1'b0 == ap_block_pp0_stage7_11001) & (icmp_ln708_reg_1472 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter1_pix_val_V_109_reg_683 <= {{img_dout[39:32]}};
    end else if (((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter1_pix_val_V_109_reg_683 <= ap_phi_reg_pp0_iter0_pix_val_V_109_reg_683;
    end
end

always @ (posedge ap_clk) begin
    if (((or_ln713_6_reg_1573 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln708_reg_1472 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_pix_val_V_110_reg_673 <= ap_phi_reg_pp0_iter1_pix_val_V_102_reg_607;
    end else if (((or_ln713_6_reg_1573 == 1'd1) & (1'b0 == ap_block_pp0_stage7_11001) & (icmp_ln708_reg_1472 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter1_pix_val_V_110_reg_673 <= {{img_dout[47:40]}};
    end else if (((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter1_pix_val_V_110_reg_673 <= ap_phi_reg_pp0_iter0_pix_val_V_110_reg_673;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln708_reg_1472 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln713_7_reg_1577 == 1'd1))) begin
        ap_phi_reg_pp0_iter1_pix_val_V_113_reg_783 <= pix_val_V_111_fu_1138_p1;
    end else if (((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter1_pix_val_V_113_reg_783 <= ap_phi_reg_pp0_iter0_pix_val_V_113_reg_783;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln708_reg_1472 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln713_7_reg_1577 == 1'd1))) begin
        ap_phi_reg_pp0_iter1_pix_val_V_114_reg_773 <= {{img_dout[15:8]}};
    end else if (((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter1_pix_val_V_114_reg_773 <= ap_phi_reg_pp0_iter0_pix_val_V_114_reg_773;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln708_reg_1472 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln713_7_reg_1577 == 1'd1))) begin
        ap_phi_reg_pp0_iter1_pix_val_V_115_reg_763 <= {{img_dout[23:16]}};
    end else if (((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter1_pix_val_V_115_reg_763 <= ap_phi_reg_pp0_iter0_pix_val_V_115_reg_763;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln708_reg_1472 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln713_7_reg_1577 == 1'd1))) begin
        ap_phi_reg_pp0_iter1_pix_val_V_116_reg_753 <= {{img_dout[31:24]}};
    end else if (((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter1_pix_val_V_116_reg_753 <= ap_phi_reg_pp0_iter0_pix_val_V_116_reg_753;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln708_reg_1472 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln713_7_reg_1577 == 1'd1))) begin
        ap_phi_reg_pp0_iter1_pix_val_V_117_reg_743 <= {{img_dout[39:32]}};
    end else if (((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter1_pix_val_V_117_reg_743 <= ap_phi_reg_pp0_iter0_pix_val_V_117_reg_743;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln708_reg_1472 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln713_7_reg_1577 == 1'd1))) begin
        ap_phi_reg_pp0_iter1_pix_val_V_118_reg_733 <= {{img_dout[47:40]}};
    end else if (((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter1_pix_val_V_118_reg_733 <= ap_phi_reg_pp0_iter0_pix_val_V_118_reg_733;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_540)) begin
        if (((icmp_ln708_reg_1472 == 1'd0) & (or_ln713_5_reg_1569 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_pix_val_V_97_reg_662 <= ap_phi_reg_pp0_iter0_pix_val_V_89_reg_596;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_pix_val_V_97_reg_662 <= ap_phi_reg_pp0_iter0_pix_val_V_97_reg_662;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_540)) begin
        if (((icmp_ln708_reg_1472 == 1'd0) & (or_ln713_5_reg_1569 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_pix_val_V_98_reg_651 <= ap_phi_reg_pp0_iter0_pix_val_V_90_reg_585;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_pix_val_V_98_reg_651 <= ap_phi_reg_pp0_iter0_pix_val_V_98_reg_651;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_540)) begin
        if (((icmp_ln708_reg_1472 == 1'd0) & (or_ln713_5_reg_1569 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_pix_val_V_99_reg_640 <= ap_phi_reg_pp0_iter0_pix_val_V_91_reg_574;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_pix_val_V_99_reg_640 <= ap_phi_reg_pp0_iter0_pix_val_V_99_reg_640;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pix_val_V_38_fu_136 <= pix_val_V_51;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        pix_val_V_38_fu_136 <= ap_phi_mux_pix_val_V_114_phi_fu_776_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pix_val_V_39_fu_140 <= pix_val_V_52;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        pix_val_V_39_fu_140 <= ap_phi_mux_pix_val_V_115_phi_fu_766_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pix_val_V_40_fu_144 <= pix_val_V_53;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        pix_val_V_40_fu_144 <= ap_phi_mux_pix_val_V_116_phi_fu_756_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pix_val_V_41_fu_148 <= pix_val_V_54;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        pix_val_V_41_fu_148 <= ap_phi_mux_pix_val_V_117_phi_fu_746_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pix_val_V_42_fu_152 <= pix_val_V_55;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        pix_val_V_42_fu_152 <= ap_phi_mux_pix_val_V_118_phi_fu_736_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pix_val_V_fu_132 <= pix_val_V_50;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        pix_val_V_fu_132 <= ap_phi_mux_pix_val_V_113_phi_fu_786_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln708_fu_976_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            x_fu_128 <= x_4_fu_982_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            x_fu_128 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage6_11001) & (icmp_ln708_reg_1472 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (or_ln713_5_reg_1569 == 1'd1))) begin
        ap_phi_reg_pp0_iter0_pix_val_V_100_reg_629 <= {{img_dout[31:24]}};
        ap_phi_reg_pp0_iter0_pix_val_V_101_reg_618 <= {{img_dout[39:32]}};
        ap_phi_reg_pp0_iter0_pix_val_V_102_reg_607 <= {{img_dout[47:40]}};
        ap_phi_reg_pp0_iter0_pix_val_V_97_reg_662 <= pix_val_V_95_fu_1130_p1;
        ap_phi_reg_pp0_iter0_pix_val_V_98_reg_651 <= {{img_dout[15:8]}};
        ap_phi_reg_pp0_iter0_pix_val_V_99_reg_640 <= {{img_dout[23:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln708_fu_976_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cmp354_reg_1476 <= cmp354_fu_992_p2;
        or_ln713_reg_1487 <= or_ln713_fu_998_p2;
        or_ln725_1_reg_1495 <= or_ln725_1_fu_1010_p2;
        or_ln725_2_reg_1499 <= or_ln725_2_fu_1016_p2;
        or_ln725_reg_1491 <= or_ln725_fu_1004_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln708_reg_1472 <= icmp_ln708_fu_976_p2;
        icmp_ln708_reg_1472_pp0_iter1_reg <= icmp_ln708_reg_1472;
        or_ln725_2_reg_1499_pp0_iter1_reg <= or_ln725_2_reg_1499;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln708_reg_1472 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        or_ln713_1_reg_1508 <= or_ln713_1_fu_1031_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (icmp_ln708_reg_1472 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        or_ln713_2_reg_1547 <= or_ln713_2_fu_1057_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (icmp_ln708_reg_1472 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        or_ln713_3_reg_1556 <= or_ln713_3_fu_1065_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (icmp_ln708_reg_1472 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        or_ln713_4_reg_1565 <= or_ln713_4_fu_1073_p2;
        or_ln713_5_reg_1569 <= or_ln713_5_fu_1077_p2;
        or_ln713_6_reg_1573 <= or_ln713_6_fu_1081_p2;
        or_ln713_7_reg_1577 <= or_ln713_7_fu_1085_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pix_val_V_100_reg_629 <= ap_phi_reg_pp0_iter1_pix_val_V_100_reg_629;
        pix_val_V_101_reg_618 <= ap_phi_reg_pp0_iter1_pix_val_V_101_reg_618;
        pix_val_V_102_reg_607 <= ap_phi_reg_pp0_iter1_pix_val_V_102_reg_607;
        pix_val_V_97_reg_662 <= ap_phi_reg_pp0_iter1_pix_val_V_97_reg_662;
        pix_val_V_98_reg_651 <= ap_phi_reg_pp0_iter1_pix_val_V_98_reg_651;
        pix_val_V_99_reg_640 <= ap_phi_reg_pp0_iter1_pix_val_V_99_reg_640;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        pix_val_V_57_reg_333 <= ap_phi_reg_pp0_iter0_pix_val_V_57_reg_333;
        pix_val_V_58_reg_323 <= ap_phi_reg_pp0_iter0_pix_val_V_58_reg_323;
        pix_val_V_59_reg_313 <= ap_phi_reg_pp0_iter0_pix_val_V_59_reg_313;
        pix_val_V_60_reg_303 <= ap_phi_reg_pp0_iter0_pix_val_V_60_reg_303;
        pix_val_V_61_reg_293 <= ap_phi_reg_pp0_iter0_pix_val_V_61_reg_293;
        pix_val_V_62_reg_283 <= ap_phi_reg_pp0_iter0_pix_val_V_62_reg_283;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        pix_val_V_65_reg_398 <= ap_phi_reg_pp0_iter0_pix_val_V_65_reg_398;
        pix_val_V_66_reg_387 <= ap_phi_reg_pp0_iter0_pix_val_V_66_reg_387;
        pix_val_V_67_reg_376 <= ap_phi_reg_pp0_iter0_pix_val_V_67_reg_376;
        pix_val_V_68_reg_365 <= ap_phi_reg_pp0_iter0_pix_val_V_68_reg_365;
        pix_val_V_69_reg_354 <= ap_phi_reg_pp0_iter0_pix_val_V_69_reg_354;
        pix_val_V_70_reg_343 <= ap_phi_reg_pp0_iter0_pix_val_V_70_reg_343;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        pix_val_V_73_reg_464 <= ap_phi_reg_pp0_iter0_pix_val_V_73_reg_464;
        pix_val_V_74_reg_453 <= ap_phi_reg_pp0_iter0_pix_val_V_74_reg_453;
        pix_val_V_75_reg_442 <= ap_phi_reg_pp0_iter0_pix_val_V_75_reg_442;
        pix_val_V_76_reg_431 <= ap_phi_reg_pp0_iter0_pix_val_V_76_reg_431;
        pix_val_V_77_reg_420 <= ap_phi_reg_pp0_iter0_pix_val_V_77_reg_420;
        pix_val_V_78_reg_409 <= ap_phi_reg_pp0_iter0_pix_val_V_78_reg_409;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        pix_val_V_81_reg_530 <= ap_phi_reg_pp0_iter0_pix_val_V_81_reg_530;
        pix_val_V_82_reg_519 <= ap_phi_reg_pp0_iter0_pix_val_V_82_reg_519;
        pix_val_V_83_reg_508 <= ap_phi_reg_pp0_iter0_pix_val_V_83_reg_508;
        pix_val_V_84_reg_497 <= ap_phi_reg_pp0_iter0_pix_val_V_84_reg_497;
        pix_val_V_85_reg_486 <= ap_phi_reg_pp0_iter0_pix_val_V_85_reg_486;
        pix_val_V_86_reg_475 <= ap_phi_reg_pp0_iter0_pix_val_V_86_reg_475;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        pix_val_V_89_reg_596 <= ap_phi_reg_pp0_iter0_pix_val_V_89_reg_596;
        pix_val_V_90_reg_585 <= ap_phi_reg_pp0_iter0_pix_val_V_90_reg_585;
        pix_val_V_91_reg_574 <= ap_phi_reg_pp0_iter0_pix_val_V_91_reg_574;
        pix_val_V_92_reg_563 <= ap_phi_reg_pp0_iter0_pix_val_V_92_reg_563;
        pix_val_V_93_reg_552 <= ap_phi_reg_pp0_iter0_pix_val_V_93_reg_552;
        pix_val_V_94_reg_541 <= ap_phi_reg_pp0_iter0_pix_val_V_94_reg_541;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone) & (icmp_ln708_reg_1472 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln708_reg_1472_pp0_iter1_reg == 1'd0) & (or_ln713_7_reg_1577 == 1'd0))) begin
        ap_phi_mux_pix_val_V_113_phi_fu_786_p4 = ap_phi_reg_pp0_iter1_pix_val_V_105_reg_723;
    end else begin
        ap_phi_mux_pix_val_V_113_phi_fu_786_p4 = ap_phi_reg_pp0_iter1_pix_val_V_113_reg_783;
    end
end

always @ (*) begin
    if (((icmp_ln708_reg_1472_pp0_iter1_reg == 1'd0) & (or_ln713_7_reg_1577 == 1'd0))) begin
        ap_phi_mux_pix_val_V_114_phi_fu_776_p4 = ap_phi_reg_pp0_iter1_pix_val_V_106_reg_713;
    end else begin
        ap_phi_mux_pix_val_V_114_phi_fu_776_p4 = ap_phi_reg_pp0_iter1_pix_val_V_114_reg_773;
    end
end

always @ (*) begin
    if (((icmp_ln708_reg_1472_pp0_iter1_reg == 1'd0) & (or_ln713_7_reg_1577 == 1'd0))) begin
        ap_phi_mux_pix_val_V_115_phi_fu_766_p4 = ap_phi_reg_pp0_iter1_pix_val_V_107_reg_703;
    end else begin
        ap_phi_mux_pix_val_V_115_phi_fu_766_p4 = ap_phi_reg_pp0_iter1_pix_val_V_115_reg_763;
    end
end

always @ (*) begin
    if (((icmp_ln708_reg_1472_pp0_iter1_reg == 1'd0) & (or_ln713_7_reg_1577 == 1'd0))) begin
        ap_phi_mux_pix_val_V_116_phi_fu_756_p4 = ap_phi_reg_pp0_iter1_pix_val_V_108_reg_693;
    end else begin
        ap_phi_mux_pix_val_V_116_phi_fu_756_p4 = ap_phi_reg_pp0_iter1_pix_val_V_116_reg_753;
    end
end

always @ (*) begin
    if (((icmp_ln708_reg_1472_pp0_iter1_reg == 1'd0) & (or_ln713_7_reg_1577 == 1'd0))) begin
        ap_phi_mux_pix_val_V_117_phi_fu_746_p4 = ap_phi_reg_pp0_iter1_pix_val_V_109_reg_683;
    end else begin
        ap_phi_mux_pix_val_V_117_phi_fu_746_p4 = ap_phi_reg_pp0_iter1_pix_val_V_117_reg_743;
    end
end

always @ (*) begin
    if (((icmp_ln708_reg_1472_pp0_iter1_reg == 1'd0) & (or_ln713_7_reg_1577 == 1'd0))) begin
        ap_phi_mux_pix_val_V_118_phi_fu_736_p4 = ap_phi_reg_pp0_iter1_pix_val_V_110_reg_673;
    end else begin
        ap_phi_mux_pix_val_V_118_phi_fu_736_p4 = ap_phi_reg_pp0_iter1_pix_val_V_118_reg_733;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage7_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_x_3 = 10'd0;
    end else begin
        ap_sig_allocacmp_x_3 = x_fu_128;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (or_ln725_2_reg_1499_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage5) & (icmp_ln708_reg_1472 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (or_ln725_reg_1491 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (or_ln725_1_reg_1495 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        bytePlanes_01_blk_n = bytePlanes_01_full_n;
    end else begin
        bytePlanes_01_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (or_ln725_2_reg_1499_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        bytePlanes_01_din = p_0_fu_1279_p17;
    end else if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (or_ln725_1_reg_1495 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bytePlanes_01_din = p_1_fu_1142_p17;
    end else if (((1'b0 == ap_block_pp0_stage5_01001) & (ap_predicate_op143_write_state6 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        bytePlanes_01_din = p_s_fu_1093_p17;
    end else begin
        bytePlanes_01_din = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (or_ln725_1_reg_1495 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_predicate_op143_write_state6 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (or_ln725_2_reg_1499_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        bytePlanes_01_write = 1'b1;
    end else begin
        bytePlanes_01_write = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_op167_read_state8 == 1'b1) & (1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage1) & (icmp_ln708_reg_1472 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (or_ln713_reg_1487 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage2) & (ap_predicate_op83_read_state3 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage3) & (icmp_ln708_reg_1472 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (or_ln713_2_reg_1547 == 1'd1)) | ((1'b0 == ap_block_pp0_stage4) & (icmp_ln708_reg_1472 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (or_ln713_3_reg_1556 == 1'd1)) | ((1'b0 == ap_block_pp0_stage5) & (icmp_ln708_reg_1472 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (or_ln713_4_reg_1565 == 1'd1)) | ((1'b0 == ap_block_pp0_stage6) & (icmp_ln708_reg_1472 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (or_ln713_5_reg_1569 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0) & (icmp_ln708_reg_1472 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln713_7_reg_1577 == 1'd1)))) begin
        img_blk_n = img_empty_n;
    end else begin
        img_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_predicate_op167_read_state8 == 1'b1) & (1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_predicate_op152_read_state7 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_predicate_op99_read_state4 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op182_read_state9 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_predicate_op134_read_state6 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_predicate_op83_read_state3 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_predicate_op115_read_state5 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_predicate_op64_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        img_read = 1'b1;
    end else begin
        img_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        out_pix_V_23_out_ap_vld = 1'b1;
    end else begin
        out_pix_V_23_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (icmp_ln708_reg_1472 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        pix_val_V_58_out_ap_vld = 1'b1;
    end else begin
        pix_val_V_58_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (icmp_ln708_reg_1472 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        pix_val_V_59_out_ap_vld = 1'b1;
    end else begin
        pix_val_V_59_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (icmp_ln708_reg_1472 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        pix_val_V_60_out_ap_vld = 1'b1;
    end else begin
        pix_val_V_60_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (icmp_ln708_reg_1472 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        pix_val_V_61_out_ap_vld = 1'b1;
    end else begin
        pix_val_V_61_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (icmp_ln708_reg_1472 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        pix_val_V_62_out_ap_vld = 1'b1;
    end else begin
        pix_val_V_62_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (icmp_ln708_reg_1472 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        pix_val_V_63_out_ap_vld = 1'b1;
    end else begin
        pix_val_V_63_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b1 == ap_condition_exit_pp0_iter0_stage2)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp0_stage7 = ap_CS_fsm[32'd7];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((img_empty_n == 1'b0) & (ap_predicate_op182_read_state9 == 1'b1)) | ((or_ln725_1_reg_1495 == 1'd1) & (bytePlanes_01_full_n == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((img_empty_n == 1'b0) & (ap_predicate_op182_read_state9 == 1'b1)) | ((or_ln725_1_reg_1495 == 1'd1) & (bytePlanes_01_full_n == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((img_empty_n == 1'b0) & (ap_predicate_op182_read_state9 == 1'b1)) | ((or_ln725_1_reg_1495 == 1'd1) & (bytePlanes_01_full_n == 1'b0))));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_01001 = (((img_empty_n == 1'b0) & (ap_predicate_op64_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (or_ln725_2_reg_1499_pp0_iter1_reg == 1'd1) & (bytePlanes_01_full_n == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage1_11001 = (((img_empty_n == 1'b0) & (ap_predicate_op64_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (or_ln725_2_reg_1499_pp0_iter1_reg == 1'd1) & (bytePlanes_01_full_n == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = (((img_empty_n == 1'b0) & (ap_predicate_op64_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (or_ln725_2_reg_1499_pp0_iter1_reg == 1'd1) & (bytePlanes_01_full_n == 1'b0)));
end

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_11001 = ((ap_predicate_op83_read_state3 == 1'b1) & (img_empty_n == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage2_subdone = ((ap_predicate_op83_read_state3 == 1'b1) & (img_empty_n == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_11001 = ((img_empty_n == 1'b0) & (ap_predicate_op99_read_state4 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage3_subdone = ((img_empty_n == 1'b0) & (ap_predicate_op99_read_state4 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage4_11001 = ((img_empty_n == 1'b0) & (ap_predicate_op115_read_state5 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage4_subdone = ((img_empty_n == 1'b0) & (ap_predicate_op115_read_state5 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

assign ap_block_pp0_stage5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage5_01001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (((img_empty_n == 1'b0) & (ap_predicate_op134_read_state6 == 1'b1)) | ((ap_predicate_op143_write_state6 == 1'b1) & (bytePlanes_01_full_n == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage5_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (((img_empty_n == 1'b0) & (ap_predicate_op134_read_state6 == 1'b1)) | ((ap_predicate_op143_write_state6 == 1'b1) & (bytePlanes_01_full_n == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage5_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & (((img_empty_n == 1'b0) & (ap_predicate_op134_read_state6 == 1'b1)) | ((ap_predicate_op143_write_state6 == 1'b1) & (bytePlanes_01_full_n == 1'b0))));
end

assign ap_block_pp0_stage6 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage6_11001 = ((img_empty_n == 1'b0) & (ap_predicate_op152_read_state7 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage6_subdone = ((img_empty_n == 1'b0) & (ap_predicate_op152_read_state7 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

assign ap_block_pp0_stage7 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage7_11001 = ((ap_predicate_op167_read_state8 == 1'b1) & (img_empty_n == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage7_subdone = ((ap_predicate_op167_read_state8 == 1'b1) & (img_empty_n == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_state10_pp0_stage1_iter1 = ((or_ln725_2_reg_1499_pp0_iter1_reg == 1'd1) & (bytePlanes_01_full_n == 1'b0));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage1_iter0 = ((img_empty_n == 1'b0) & (ap_predicate_op64_read_state2 == 1'b1));
end

always @ (*) begin
    ap_block_state3_pp0_stage2_iter0 = ((ap_predicate_op83_read_state3 == 1'b1) & (img_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state4_pp0_stage3_iter0 = ((img_empty_n == 1'b0) & (ap_predicate_op99_read_state4 == 1'b1));
end

always @ (*) begin
    ap_block_state5_pp0_stage4_iter0 = ((img_empty_n == 1'b0) & (ap_predicate_op115_read_state5 == 1'b1));
end

always @ (*) begin
    ap_block_state6_pp0_stage5_iter0 = (((img_empty_n == 1'b0) & (ap_predicate_op134_read_state6 == 1'b1)) | ((ap_predicate_op143_write_state6 == 1'b1) & (bytePlanes_01_full_n == 1'b0)));
end

always @ (*) begin
    ap_block_state7_pp0_stage6_iter0 = ((img_empty_n == 1'b0) & (ap_predicate_op152_read_state7 == 1'b1));
end

always @ (*) begin
    ap_block_state8_pp0_stage7_iter0 = ((ap_predicate_op167_read_state8 == 1'b1) & (img_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state9_pp0_stage0_iter1 = (((img_empty_n == 1'b0) & (ap_predicate_op182_read_state9 == 1'b1)) | ((or_ln725_1_reg_1495 == 1'd1) & (bytePlanes_01_full_n == 1'b0)));
end

always @ (*) begin
    ap_condition_1133 = ((1'b0 == ap_block_pp0_stage1_11001) & (or_ln713_reg_1487 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1));
end

always @ (*) begin
    ap_condition_1137 = ((1'b0 == ap_block_pp0_stage2_11001) & (or_ln713_reg_1487 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2));
end

always @ (*) begin
    ap_condition_1141 = ((1'b0 == ap_block_pp0_stage2_11001) & (or_ln713_1_reg_1508 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2));
end

always @ (*) begin
    ap_condition_1145 = ((1'b0 == ap_block_pp0_stage3_11001) & (or_ln713_1_reg_1508 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage3));
end

always @ (*) begin
    ap_condition_1148 = ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (or_ln713_2_reg_1547 == 1'd1));
end

always @ (*) begin
    ap_condition_1151 = ((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4) & (or_ln713_2_reg_1547 == 1'd0));
end

always @ (*) begin
    ap_condition_1154 = ((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4) & (or_ln713_3_reg_1556 == 1'd1));
end

always @ (*) begin
    ap_condition_1157 = ((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5) & (or_ln713_3_reg_1556 == 1'd0));
end

always @ (*) begin
    ap_condition_1160 = ((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5) & (or_ln713_4_reg_1565 == 1'd1));
end

always @ (*) begin
    ap_condition_1163 = ((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6) & (or_ln713_4_reg_1565 == 1'd0));
end

always @ (*) begin
    ap_condition_540 = ((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage2;

assign ap_phi_reg_pp0_iter0_pix_val_V_105_reg_723 = 'bx;

assign ap_phi_reg_pp0_iter0_pix_val_V_106_reg_713 = 'bx;

assign ap_phi_reg_pp0_iter0_pix_val_V_107_reg_703 = 'bx;

assign ap_phi_reg_pp0_iter0_pix_val_V_108_reg_693 = 'bx;

assign ap_phi_reg_pp0_iter0_pix_val_V_109_reg_683 = 'bx;

assign ap_phi_reg_pp0_iter0_pix_val_V_110_reg_673 = 'bx;

assign ap_phi_reg_pp0_iter0_pix_val_V_113_reg_783 = 'bx;

assign ap_phi_reg_pp0_iter0_pix_val_V_114_reg_773 = 'bx;

assign ap_phi_reg_pp0_iter0_pix_val_V_115_reg_763 = 'bx;

assign ap_phi_reg_pp0_iter0_pix_val_V_116_reg_753 = 'bx;

assign ap_phi_reg_pp0_iter0_pix_val_V_117_reg_743 = 'bx;

assign ap_phi_reg_pp0_iter0_pix_val_V_118_reg_733 = 'bx;

always @ (*) begin
    ap_predicate_op115_read_state5 = ((icmp_ln708_reg_1472 == 1'd0) & (or_ln713_3_reg_1556 == 1'd1));
end

always @ (*) begin
    ap_predicate_op134_read_state6 = ((icmp_ln708_reg_1472 == 1'd0) & (or_ln713_4_reg_1565 == 1'd1));
end

always @ (*) begin
    ap_predicate_op143_write_state6 = ((icmp_ln708_reg_1472 == 1'd0) & (or_ln725_reg_1491 == 1'd1));
end

always @ (*) begin
    ap_predicate_op152_read_state7 = ((icmp_ln708_reg_1472 == 1'd0) & (or_ln713_5_reg_1569 == 1'd1));
end

always @ (*) begin
    ap_predicate_op167_read_state8 = ((or_ln713_6_reg_1573 == 1'd1) & (icmp_ln708_reg_1472 == 1'd0));
end

always @ (*) begin
    ap_predicate_op182_read_state9 = ((icmp_ln708_reg_1472 == 1'd0) & (or_ln713_7_reg_1577 == 1'd1));
end

always @ (*) begin
    ap_predicate_op64_read_state2 = ((icmp_ln708_reg_1472 == 1'd0) & (or_ln713_reg_1487 == 1'd1));
end

always @ (*) begin
    ap_predicate_op83_read_state3 = ((or_ln713_1_reg_1508 == 1'd1) & (icmp_ln708_reg_1472 == 1'd0));
end

always @ (*) begin
    ap_predicate_op99_read_state4 = ((icmp_ln708_reg_1472 == 1'd0) & (or_ln713_2_reg_1547 == 1'd1));
end

assign cmp354_fu_992_p2 = (($signed(zext_ln708_fu_988_p1) < $signed(sub353)) ? 1'b1 : 1'b0);

assign icmp_ln708_fu_976_p2 = ((ap_sig_allocacmp_x_3 == trunc_ln5) ? 1'b1 : 1'b0);

assign or_ln713_1_fu_1031_p2 = (cmp355_1 | cmp354_reg_1476);

assign or_ln713_2_fu_1057_p2 = (cmp355_2 | cmp354_reg_1476);

assign or_ln713_3_fu_1065_p2 = (cmp355_3 | cmp354_reg_1476);

assign or_ln713_4_fu_1073_p2 = (cmp355_4 | cmp354_reg_1476);

assign or_ln713_5_fu_1077_p2 = (cmp355_5 | cmp354_reg_1476);

assign or_ln713_6_fu_1081_p2 = (cmp355_6 | cmp354_reg_1476);

assign or_ln713_7_fu_1085_p2 = (icmp_ln698 | cmp354_reg_1476);

assign or_ln713_fu_998_p2 = (cmp355 | cmp354_fu_992_p2);

assign or_ln725_1_fu_1010_p2 = (cmp388_1 | cmp354_fu_992_p2);

assign or_ln725_2_fu_1016_p2 = (cmp388_2 | cmp354_fu_992_p2);

assign or_ln725_fu_1004_p2 = (cmp388 | cmp354_fu_992_p2);

assign out_pix_V_23_out = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{ap_phi_mux_pix_val_V_118_phi_fu_736_p4}, {ap_phi_mux_pix_val_V_117_phi_fu_746_p4}}, {ap_phi_mux_pix_val_V_116_phi_fu_756_p4}}, {ap_phi_mux_pix_val_V_115_phi_fu_766_p4}}, {ap_phi_mux_pix_val_V_114_phi_fu_776_p4}}, {ap_phi_mux_pix_val_V_113_phi_fu_786_p4}}, {ap_phi_reg_pp0_iter1_pix_val_V_110_reg_673}}, {ap_phi_reg_pp0_iter1_pix_val_V_109_reg_683}}, {ap_phi_reg_pp0_iter1_pix_val_V_108_reg_693}}, {ap_phi_reg_pp0_iter1_pix_val_V_107_reg_703}}, {ap_phi_reg_pp0_iter1_pix_val_V_106_reg_713}}, {ap_phi_reg_pp0_iter1_pix_val_V_105_reg_723}}, {pix_val_V_102_reg_607}}, {pix_val_V_101_reg_618}}, {pix_val_V_100_reg_629}}, {pix_val_V_99_reg_640}}, {pix_val_V_98_reg_651}}, {pix_val_V_97_reg_662}}, {pix_val_V_94_reg_541}}, {pix_val_V_93_reg_552}}, {pix_val_V_92_reg_563}}, {pix_val_V_91_reg_574}}, {pix_val_V_90_reg_585}}, {pix_val_V_89_reg_596}}, {pix_val_V_86_reg_475}}, {pix_val_V_85_reg_486}}, {pix_val_V_84_reg_497}}, {pix_val_V_83_reg_508}}, {pix_val_V_82_reg_519}}, {pix_val_V_81_reg_530}}, {pix_val_V_78_reg_409}}, {pix_val_V_77_reg_420}}, {pix_val_V_76_reg_431}}, {pix_val_V_75_reg_442}}, {pix_val_V_74_reg_453}}, {pix_val_V_73_reg_464}}, {pix_val_V_70_reg_343}}, {pix_val_V_69_reg_354}}, {pix_val_V_68_reg_365}}, {pix_val_V_67_reg_376}}, {pix_val_V_66_reg_387}}, {pix_val_V_65_reg_398}}, {pix_val_V_62_reg_283}}, {pix_val_V_61_reg_293}}, {pix_val_V_60_reg_303}}, {pix_val_V_59_reg_313}}, {pix_val_V_58_reg_323}}, {pix_val_V_57_reg_333}};

assign p_0_fu_1279_p17 = {{{{{{{{{{{{{{{{ap_phi_mux_pix_val_V_118_phi_fu_736_p4}, {ap_phi_mux_pix_val_V_117_phi_fu_746_p4}}, {ap_phi_mux_pix_val_V_116_phi_fu_756_p4}}, {ap_phi_mux_pix_val_V_115_phi_fu_766_p4}}, {ap_phi_mux_pix_val_V_114_phi_fu_776_p4}}, {ap_phi_mux_pix_val_V_113_phi_fu_786_p4}}, {ap_phi_reg_pp0_iter1_pix_val_V_110_reg_673}}, {ap_phi_reg_pp0_iter1_pix_val_V_109_reg_683}}, {ap_phi_reg_pp0_iter1_pix_val_V_108_reg_693}}, {ap_phi_reg_pp0_iter1_pix_val_V_107_reg_703}}, {ap_phi_reg_pp0_iter1_pix_val_V_106_reg_713}}, {ap_phi_reg_pp0_iter1_pix_val_V_105_reg_723}}, {pix_val_V_102_reg_607}}, {pix_val_V_101_reg_618}}, {pix_val_V_100_reg_629}}, {pix_val_V_99_reg_640}};

assign p_1_fu_1142_p17 = {{{{{{{{{{{{{{{{ap_phi_reg_pp0_iter1_pix_val_V_98_reg_651}, {ap_phi_reg_pp0_iter1_pix_val_V_97_reg_662}}, {pix_val_V_94_reg_541}}, {pix_val_V_93_reg_552}}, {pix_val_V_92_reg_563}}, {pix_val_V_91_reg_574}}, {pix_val_V_90_reg_585}}, {pix_val_V_89_reg_596}}, {pix_val_V_86_reg_475}}, {pix_val_V_85_reg_486}}, {pix_val_V_84_reg_497}}, {pix_val_V_83_reg_508}}, {pix_val_V_82_reg_519}}, {pix_val_V_81_reg_530}}, {pix_val_V_78_reg_409}}, {pix_val_V_77_reg_420}};

assign p_s_fu_1093_p17 = {{{{{{{{{{{{{{{{ap_phi_reg_pp0_iter0_pix_val_V_76_reg_431}, {ap_phi_reg_pp0_iter0_pix_val_V_75_reg_442}}, {ap_phi_reg_pp0_iter0_pix_val_V_74_reg_453}}, {ap_phi_reg_pp0_iter0_pix_val_V_73_reg_464}}, {pix_val_V_70_reg_343}}, {pix_val_V_69_reg_354}}, {pix_val_V_68_reg_365}}, {pix_val_V_67_reg_376}}, {pix_val_V_66_reg_387}}, {pix_val_V_65_reg_398}}, {pix_val_V_62_reg_283}}, {pix_val_V_61_reg_293}}, {pix_val_V_60_reg_303}}, {pix_val_V_59_reg_313}}, {pix_val_V_58_reg_323}}, {pix_val_V_57_reg_333}};

assign pix_val_V_103_fu_1134_p1 = img_dout[7:0];

assign pix_val_V_111_fu_1138_p1 = img_dout[7:0];

assign pix_val_V_49_fu_1027_p1 = img_dout[7:0];

assign pix_val_V_58_out = pix_val_V_fu_132;

assign pix_val_V_59_out = pix_val_V_38_fu_136;

assign pix_val_V_60_out = pix_val_V_39_fu_140;

assign pix_val_V_61_out = pix_val_V_40_fu_144;

assign pix_val_V_62_out = pix_val_V_41_fu_148;

assign pix_val_V_63_fu_1053_p1 = img_dout[7:0];

assign pix_val_V_63_out = pix_val_V_42_fu_152;

assign pix_val_V_71_fu_1061_p1 = img_dout[7:0];

assign pix_val_V_79_fu_1069_p1 = img_dout[7:0];

assign pix_val_V_87_fu_1089_p1 = img_dout[7:0];

assign pix_val_V_95_fu_1130_p1 = img_dout[7:0];

assign x_4_fu_982_p2 = (ap_sig_allocacmp_x_3 + 10'd1);

assign zext_ln708_fu_988_p1 = ap_sig_allocacmp_x_3;

endmodule //design_1_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_708_18
