// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module design_1_v_frmbuf_wr_0_0_Bytes2AXIMMvideo (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        bytePlanes_01_dout,
        bytePlanes_01_empty_n,
        bytePlanes_01_read,
        bytePlanes_12_dout,
        bytePlanes_12_empty_n,
        bytePlanes_12_read,
        m_axi_mm_video_AWVALID,
        m_axi_mm_video_AWREADY,
        m_axi_mm_video_AWADDR,
        m_axi_mm_video_AWID,
        m_axi_mm_video_AWLEN,
        m_axi_mm_video_AWSIZE,
        m_axi_mm_video_AWBURST,
        m_axi_mm_video_AWLOCK,
        m_axi_mm_video_AWCACHE,
        m_axi_mm_video_AWPROT,
        m_axi_mm_video_AWQOS,
        m_axi_mm_video_AWREGION,
        m_axi_mm_video_AWUSER,
        m_axi_mm_video_WVALID,
        m_axi_mm_video_WREADY,
        m_axi_mm_video_WDATA,
        m_axi_mm_video_WSTRB,
        m_axi_mm_video_WLAST,
        m_axi_mm_video_WID,
        m_axi_mm_video_WUSER,
        m_axi_mm_video_ARVALID,
        m_axi_mm_video_ARREADY,
        m_axi_mm_video_ARADDR,
        m_axi_mm_video_ARID,
        m_axi_mm_video_ARLEN,
        m_axi_mm_video_ARSIZE,
        m_axi_mm_video_ARBURST,
        m_axi_mm_video_ARLOCK,
        m_axi_mm_video_ARCACHE,
        m_axi_mm_video_ARPROT,
        m_axi_mm_video_ARQOS,
        m_axi_mm_video_ARREGION,
        m_axi_mm_video_ARUSER,
        m_axi_mm_video_RVALID,
        m_axi_mm_video_RREADY,
        m_axi_mm_video_RDATA,
        m_axi_mm_video_RLAST,
        m_axi_mm_video_RID,
        m_axi_mm_video_RFIFONUM,
        m_axi_mm_video_RUSER,
        m_axi_mm_video_RRESP,
        m_axi_mm_video_BVALID,
        m_axi_mm_video_BREADY,
        m_axi_mm_video_BRESP,
        m_axi_mm_video_BID,
        m_axi_mm_video_BUSER,
        dstImg_dout,
        dstImg_empty_n,
        dstImg_read,
        dstImg2_dout,
        dstImg2_empty_n,
        dstImg2_read,
        Height_dout,
        Height_empty_n,
        Height_read,
        WidthInBytes_dout,
        WidthInBytes_empty_n,
        WidthInBytes_read,
        StrideInBytes_dout,
        StrideInBytes_empty_n,
        StrideInBytes_read,
        VideoFormat_dout,
        VideoFormat_empty_n,
        VideoFormat_read
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_state4 = 10'd8;
parameter    ap_ST_fsm_state5 = 10'd16;
parameter    ap_ST_fsm_state6 = 10'd32;
parameter    ap_ST_fsm_state7 = 10'd64;
parameter    ap_ST_fsm_state8 = 10'd128;
parameter    ap_ST_fsm_state9 = 10'd256;
parameter    ap_ST_fsm_state10 = 10'd512;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [127:0] bytePlanes_01_dout;
input   bytePlanes_01_empty_n;
output   bytePlanes_01_read;
input  [127:0] bytePlanes_12_dout;
input   bytePlanes_12_empty_n;
output   bytePlanes_12_read;
output   m_axi_mm_video_AWVALID;
input   m_axi_mm_video_AWREADY;
output  [31:0] m_axi_mm_video_AWADDR;
output  [0:0] m_axi_mm_video_AWID;
output  [31:0] m_axi_mm_video_AWLEN;
output  [2:0] m_axi_mm_video_AWSIZE;
output  [1:0] m_axi_mm_video_AWBURST;
output  [1:0] m_axi_mm_video_AWLOCK;
output  [3:0] m_axi_mm_video_AWCACHE;
output  [2:0] m_axi_mm_video_AWPROT;
output  [3:0] m_axi_mm_video_AWQOS;
output  [3:0] m_axi_mm_video_AWREGION;
output  [0:0] m_axi_mm_video_AWUSER;
output   m_axi_mm_video_WVALID;
input   m_axi_mm_video_WREADY;
output  [127:0] m_axi_mm_video_WDATA;
output  [15:0] m_axi_mm_video_WSTRB;
output   m_axi_mm_video_WLAST;
output  [0:0] m_axi_mm_video_WID;
output  [0:0] m_axi_mm_video_WUSER;
output   m_axi_mm_video_ARVALID;
input   m_axi_mm_video_ARREADY;
output  [31:0] m_axi_mm_video_ARADDR;
output  [0:0] m_axi_mm_video_ARID;
output  [31:0] m_axi_mm_video_ARLEN;
output  [2:0] m_axi_mm_video_ARSIZE;
output  [1:0] m_axi_mm_video_ARBURST;
output  [1:0] m_axi_mm_video_ARLOCK;
output  [3:0] m_axi_mm_video_ARCACHE;
output  [2:0] m_axi_mm_video_ARPROT;
output  [3:0] m_axi_mm_video_ARQOS;
output  [3:0] m_axi_mm_video_ARREGION;
output  [0:0] m_axi_mm_video_ARUSER;
input   m_axi_mm_video_RVALID;
output   m_axi_mm_video_RREADY;
input  [127:0] m_axi_mm_video_RDATA;
input   m_axi_mm_video_RLAST;
input  [0:0] m_axi_mm_video_RID;
input  [8:0] m_axi_mm_video_RFIFONUM;
input  [0:0] m_axi_mm_video_RUSER;
input  [1:0] m_axi_mm_video_RRESP;
input   m_axi_mm_video_BVALID;
output   m_axi_mm_video_BREADY;
input  [1:0] m_axi_mm_video_BRESP;
input  [0:0] m_axi_mm_video_BID;
input  [0:0] m_axi_mm_video_BUSER;
input  [31:0] dstImg_dout;
input   dstImg_empty_n;
output   dstImg_read;
input  [31:0] dstImg2_dout;
input   dstImg2_empty_n;
output   dstImg2_read;
input  [11:0] Height_dout;
input   Height_empty_n;
output   Height_read;
input  [14:0] WidthInBytes_dout;
input   WidthInBytes_empty_n;
output   WidthInBytes_read;
input  [15:0] StrideInBytes_dout;
input   StrideInBytes_empty_n;
output   StrideInBytes_read;
input  [5:0] VideoFormat_dout;
input   VideoFormat_empty_n;
output   VideoFormat_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg bytePlanes_01_read;
reg bytePlanes_12_read;
reg m_axi_mm_video_AWVALID;
reg[31:0] m_axi_mm_video_AWADDR;
reg[0:0] m_axi_mm_video_AWID;
reg[31:0] m_axi_mm_video_AWLEN;
reg[2:0] m_axi_mm_video_AWSIZE;
reg[1:0] m_axi_mm_video_AWBURST;
reg[1:0] m_axi_mm_video_AWLOCK;
reg[3:0] m_axi_mm_video_AWCACHE;
reg[2:0] m_axi_mm_video_AWPROT;
reg[3:0] m_axi_mm_video_AWQOS;
reg[3:0] m_axi_mm_video_AWREGION;
reg[0:0] m_axi_mm_video_AWUSER;
reg m_axi_mm_video_WVALID;
reg[127:0] m_axi_mm_video_WDATA;
reg[15:0] m_axi_mm_video_WSTRB;
reg m_axi_mm_video_WLAST;
reg[0:0] m_axi_mm_video_WID;
reg[0:0] m_axi_mm_video_WUSER;
reg m_axi_mm_video_BREADY;
reg dstImg_read;
reg dstImg2_read;
reg Height_read;
reg WidthInBytes_read;
reg StrideInBytes_read;
reg VideoFormat_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    dstImg_blk_n;
reg    dstImg2_blk_n;
reg    Height_blk_n;
reg    WidthInBytes_blk_n;
reg    StrideInBytes_blk_n;
reg    VideoFormat_blk_n;
reg   [5:0] VideoFormat_read_reg_478;
reg   [11:0] Height_read_reg_494;
reg   [31:0] dstImg2_read_reg_499;
reg   [31:0] dstImg_read_reg_504;
reg   [11:0] div_reg_509;
reg   [11:0] div5_reg_518;
wire   [31:0] div5_cast_fu_237_p1;
reg   [31:0] div5_cast_reg_524;
wire    ap_CS_fsm_state2;
wire   [0:0] cmp23_fu_243_p2;
reg   [0:0] cmp23_reg_529;
wire   [27:0] zext_ln1065_fu_255_p1;
reg   [27:0] zext_ln1065_reg_533;
wire   [0:0] icmp_ln1065_fu_275_p2;
reg   [0:0] icmp_ln1065_reg_538;
wire   [0:0] trunc_ln1053_fu_284_p1;
reg   [0:0] trunc_ln1053_reg_542;
wire    ap_CS_fsm_state3;
wire   [11:0] y_22_fu_293_p2;
reg   [11:0] y_22_reg_549;
wire   [0:0] icmp_ln1053_fu_288_p2;
reg   [27:0] trunc_ln8_reg_559;
wire    ap_CS_fsm_state6;
wire   [0:0] empty_408_fu_367_p2;
reg   [0:0] empty_408_reg_564;
wire    ap_CS_fsm_state8;
wire   [0:0] empty_417_fu_416_p2;
reg   [0:0] empty_417_reg_568;
reg   [27:0] trunc_ln9_reg_572;
wire    grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_ap_start;
wire    grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_ap_done;
wire    grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_ap_idle;
wire    grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_ap_ready;
wire    grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_AWVALID;
wire   [31:0] grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_AWADDR;
wire   [0:0] grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_AWID;
wire   [31:0] grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_AWLEN;
wire   [2:0] grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_AWSIZE;
wire   [1:0] grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_AWBURST;
wire   [1:0] grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_AWLOCK;
wire   [3:0] grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_AWCACHE;
wire   [2:0] grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_AWPROT;
wire   [3:0] grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_AWQOS;
wire   [3:0] grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_AWREGION;
wire   [0:0] grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_AWUSER;
wire    grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_WVALID;
wire   [127:0] grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_WDATA;
wire   [15:0] grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_WSTRB;
wire    grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_WLAST;
wire   [0:0] grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_WID;
wire   [0:0] grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_WUSER;
wire    grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_ARVALID;
wire   [31:0] grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_ARADDR;
wire   [0:0] grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_ARID;
wire   [31:0] grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_ARLEN;
wire   [2:0] grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_ARSIZE;
wire   [1:0] grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_ARBURST;
wire   [1:0] grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_ARLOCK;
wire   [3:0] grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_ARCACHE;
wire   [2:0] grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_ARPROT;
wire   [3:0] grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_ARQOS;
wire   [3:0] grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_ARREGION;
wire   [0:0] grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_ARUSER;
wire    grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_RREADY;
wire    grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_BREADY;
wire    grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_bytePlanes_01_read;
wire    grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_ap_start;
wire    grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_ap_done;
wire    grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_ap_idle;
wire    grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_ap_ready;
wire    grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_AWVALID;
wire   [31:0] grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_AWADDR;
wire   [0:0] grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_AWID;
wire   [31:0] grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_AWLEN;
wire   [2:0] grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_AWSIZE;
wire   [1:0] grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_AWBURST;
wire   [1:0] grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_AWLOCK;
wire   [3:0] grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_AWCACHE;
wire   [2:0] grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_AWPROT;
wire   [3:0] grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_AWQOS;
wire   [3:0] grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_AWREGION;
wire   [0:0] grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_AWUSER;
wire    grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_WVALID;
wire   [127:0] grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_WDATA;
wire   [15:0] grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_WSTRB;
wire    grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_WLAST;
wire   [0:0] grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_WID;
wire   [0:0] grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_WUSER;
wire    grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_ARVALID;
wire   [31:0] grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_ARADDR;
wire   [0:0] grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_ARID;
wire   [31:0] grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_ARLEN;
wire   [2:0] grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_ARSIZE;
wire   [1:0] grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_ARBURST;
wire   [1:0] grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_ARLOCK;
wire   [3:0] grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_ARCACHE;
wire   [2:0] grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_ARPROT;
wire   [3:0] grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_ARQOS;
wire   [3:0] grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_ARREGION;
wire   [0:0] grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_ARUSER;
wire    grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_RREADY;
wire    grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_BREADY;
wire    grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_bytePlanes_12_read;
reg    grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_ap_start_reg;
wire    ap_CS_fsm_state7;
reg    grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_ap_start_reg;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
reg   [11:0] y_fu_128;
reg    ap_predicate_op98_call_state10;
reg    ap_block_state10_on_subcall_done;
reg    ap_block_state1;
reg   [31:0] offsetUV_fu_132;
wire   [31:0] offsetUV_1_fu_443_p2;
wire   [15:0] WidthInBytes_load_cast_fu_197_p1;
wire   [15:0] sub_fu_201_p2;
wire   [15:0] and_ln_fu_248_p3;
wire   [6:0] VideoFormat_load_cast5_fu_240_p1;
wire   [6:0] add_ln1065_fu_259_p2;
wire   [5:0] tmp_fu_265_p4;
wire   [31:0] grp_fu_457_p3;
wire   [0:0] empty_399_fu_318_p2;
wire   [0:0] empty_398_fu_313_p2;
wire   [0:0] empty_401_fu_329_p2;
wire   [0:0] empty_400_fu_323_p2;
wire   [0:0] empty_403_fu_340_p2;
wire   [0:0] empty_402_fu_334_p2;
wire   [0:0] empty_405_fu_351_p2;
wire   [0:0] empty_404_fu_345_p2;
wire   [0:0] empty_407_fu_362_p2;
wire   [0:0] empty_406_fu_356_p2;
wire   [0:0] empty_410_fu_378_p2;
wire   [0:0] empty_409_fu_373_p2;
wire   [0:0] empty_412_fu_389_p2;
wire   [0:0] empty_411_fu_383_p2;
wire   [0:0] empty_414_fu_400_p2;
wire   [0:0] empty_413_fu_394_p2;
wire   [0:0] empty_416_fu_411_p2;
wire   [0:0] empty_415_fu_405_p2;
wire   [31:0] shl_ln1067_fu_422_p2;
wire   [31:0] add_ln1067_fu_428_p2;
wire   [15:0] grp_fu_457_p0;
wire   [11:0] grp_fu_457_p1;
wire    ap_CS_fsm_state5;
reg   [9:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire   [27:0] grp_fu_457_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 10'd1;
#0 grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_ap_start_reg = 1'b0;
#0 grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_ap_start_reg = 1'b0;
end

design_1_v_frmbuf_wr_0_0_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1 grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_ap_start),
    .ap_done(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_ap_done),
    .ap_idle(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_ap_idle),
    .ap_ready(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_ap_ready),
    .m_axi_mm_video_AWVALID(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_AWVALID),
    .m_axi_mm_video_AWREADY(m_axi_mm_video_AWREADY),
    .m_axi_mm_video_AWADDR(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_AWADDR),
    .m_axi_mm_video_AWID(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_AWID),
    .m_axi_mm_video_AWLEN(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_AWLEN),
    .m_axi_mm_video_AWSIZE(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_AWSIZE),
    .m_axi_mm_video_AWBURST(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_AWBURST),
    .m_axi_mm_video_AWLOCK(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_AWLOCK),
    .m_axi_mm_video_AWCACHE(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_AWCACHE),
    .m_axi_mm_video_AWPROT(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_AWPROT),
    .m_axi_mm_video_AWQOS(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_AWQOS),
    .m_axi_mm_video_AWREGION(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_AWREGION),
    .m_axi_mm_video_AWUSER(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_AWUSER),
    .m_axi_mm_video_WVALID(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_WVALID),
    .m_axi_mm_video_WREADY(m_axi_mm_video_WREADY),
    .m_axi_mm_video_WDATA(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_WDATA),
    .m_axi_mm_video_WSTRB(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_WSTRB),
    .m_axi_mm_video_WLAST(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_WLAST),
    .m_axi_mm_video_WID(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_WID),
    .m_axi_mm_video_WUSER(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_WUSER),
    .m_axi_mm_video_ARVALID(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_ARVALID),
    .m_axi_mm_video_ARREADY(1'b0),
    .m_axi_mm_video_ARADDR(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_ARADDR),
    .m_axi_mm_video_ARID(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_ARID),
    .m_axi_mm_video_ARLEN(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_ARLEN),
    .m_axi_mm_video_ARSIZE(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_ARSIZE),
    .m_axi_mm_video_ARBURST(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_ARBURST),
    .m_axi_mm_video_ARLOCK(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_ARLOCK),
    .m_axi_mm_video_ARCACHE(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_ARCACHE),
    .m_axi_mm_video_ARPROT(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_ARPROT),
    .m_axi_mm_video_ARQOS(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_ARQOS),
    .m_axi_mm_video_ARREGION(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_ARREGION),
    .m_axi_mm_video_ARUSER(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_ARUSER),
    .m_axi_mm_video_RVALID(1'b0),
    .m_axi_mm_video_RREADY(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_RREADY),
    .m_axi_mm_video_RDATA(128'd0),
    .m_axi_mm_video_RLAST(1'b0),
    .m_axi_mm_video_RID(1'd0),
    .m_axi_mm_video_RFIFONUM(9'd0),
    .m_axi_mm_video_RUSER(1'd0),
    .m_axi_mm_video_RRESP(2'd0),
    .m_axi_mm_video_BVALID(m_axi_mm_video_BVALID),
    .m_axi_mm_video_BREADY(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_BREADY),
    .m_axi_mm_video_BRESP(m_axi_mm_video_BRESP),
    .m_axi_mm_video_BID(m_axi_mm_video_BID),
    .m_axi_mm_video_BUSER(m_axi_mm_video_BUSER),
    .bytePlanes_01_dout(bytePlanes_01_dout),
    .bytePlanes_01_empty_n(bytePlanes_01_empty_n),
    .bytePlanes_01_read(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_bytePlanes_01_read),
    .sext_ln1057(trunc_ln8_reg_559),
    .div(div_reg_509),
    .div_cast2(div_reg_509)
);

design_1_v_frmbuf_wr_0_0_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2 grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_ap_start),
    .ap_done(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_ap_done),
    .ap_idle(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_ap_idle),
    .ap_ready(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_ap_ready),
    .m_axi_mm_video_AWVALID(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_AWVALID),
    .m_axi_mm_video_AWREADY(m_axi_mm_video_AWREADY),
    .m_axi_mm_video_AWADDR(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_AWADDR),
    .m_axi_mm_video_AWID(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_AWID),
    .m_axi_mm_video_AWLEN(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_AWLEN),
    .m_axi_mm_video_AWSIZE(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_AWSIZE),
    .m_axi_mm_video_AWBURST(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_AWBURST),
    .m_axi_mm_video_AWLOCK(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_AWLOCK),
    .m_axi_mm_video_AWCACHE(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_AWCACHE),
    .m_axi_mm_video_AWPROT(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_AWPROT),
    .m_axi_mm_video_AWQOS(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_AWQOS),
    .m_axi_mm_video_AWREGION(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_AWREGION),
    .m_axi_mm_video_AWUSER(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_AWUSER),
    .m_axi_mm_video_WVALID(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_WVALID),
    .m_axi_mm_video_WREADY(m_axi_mm_video_WREADY),
    .m_axi_mm_video_WDATA(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_WDATA),
    .m_axi_mm_video_WSTRB(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_WSTRB),
    .m_axi_mm_video_WLAST(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_WLAST),
    .m_axi_mm_video_WID(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_WID),
    .m_axi_mm_video_WUSER(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_WUSER),
    .m_axi_mm_video_ARVALID(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_ARVALID),
    .m_axi_mm_video_ARREADY(1'b0),
    .m_axi_mm_video_ARADDR(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_ARADDR),
    .m_axi_mm_video_ARID(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_ARID),
    .m_axi_mm_video_ARLEN(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_ARLEN),
    .m_axi_mm_video_ARSIZE(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_ARSIZE),
    .m_axi_mm_video_ARBURST(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_ARBURST),
    .m_axi_mm_video_ARLOCK(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_ARLOCK),
    .m_axi_mm_video_ARCACHE(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_ARCACHE),
    .m_axi_mm_video_ARPROT(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_ARPROT),
    .m_axi_mm_video_ARQOS(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_ARQOS),
    .m_axi_mm_video_ARREGION(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_ARREGION),
    .m_axi_mm_video_ARUSER(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_ARUSER),
    .m_axi_mm_video_RVALID(1'b0),
    .m_axi_mm_video_RREADY(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_RREADY),
    .m_axi_mm_video_RDATA(128'd0),
    .m_axi_mm_video_RLAST(1'b0),
    .m_axi_mm_video_RID(1'd0),
    .m_axi_mm_video_RFIFONUM(9'd0),
    .m_axi_mm_video_RUSER(1'd0),
    .m_axi_mm_video_RRESP(2'd0),
    .m_axi_mm_video_BVALID(m_axi_mm_video_BVALID),
    .m_axi_mm_video_BREADY(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_BREADY),
    .m_axi_mm_video_BRESP(m_axi_mm_video_BRESP),
    .m_axi_mm_video_BID(m_axi_mm_video_BID),
    .m_axi_mm_video_BUSER(m_axi_mm_video_BUSER),
    .bytePlanes_12_dout(bytePlanes_12_dout),
    .bytePlanes_12_empty_n(bytePlanes_12_empty_n),
    .bytePlanes_12_read(grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_bytePlanes_12_read),
    .sext_ln1067(trunc_ln9_reg_572),
    .div(div_reg_509),
    .div_cast2(div_reg_509)
);

design_1_v_frmbuf_wr_0_0_mac_muladd_16ns_12ns_32ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16ns_12ns_32ns_32_4_1_U220(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_457_p0),
    .din1(grp_fu_457_p1),
    .din2(dstImg_read_reg_504),
    .ce(1'b1),
    .dout(grp_fu_457_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln1053_fu_288_p2 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state6) & (cmp23_reg_529 == 1'd1))) begin
            grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_ap_start_reg <= 1'b1;
        end else if ((grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_ap_ready == 1'b1)) begin
            grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_ap_start_reg <= 1'b1;
        end else if ((grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_ap_ready == 1'b1)) begin
            grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((dstImg_empty_n == 1'b0) | (1'b0 == VideoFormat_empty_n) | (1'b0 == StrideInBytes_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0) | (dstImg2_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        offsetUV_fu_132 <= 32'd0;
    end else if (((1'b0 == ap_block_state10_on_subcall_done) & (1'b1 == ap_CS_fsm_state10) & (((((empty_417_reg_568 == 1'd0) & (icmp_ln1065_reg_538 == 1'd1)) | ((trunc_ln1053_reg_542 == 1'd0) & (icmp_ln1065_reg_538 == 1'd1))) | ((empty_417_reg_568 == 1'd0) & (empty_408_reg_564 == 1'd1))) | ((empty_408_reg_564 == 1'd1) & (trunc_ln1053_reg_542 == 1'd0))))) begin
        offsetUV_fu_132 <= offsetUV_1_fu_443_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((dstImg_empty_n == 1'b0) | (1'b0 == VideoFormat_empty_n) | (1'b0 == StrideInBytes_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0) | (dstImg2_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        y_fu_128 <= 12'd0;
    end else if (((1'b0 == ap_block_state10_on_subcall_done) & (1'b1 == ap_CS_fsm_state10))) begin
        y_fu_128 <= y_22_reg_549;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        Height_read_reg_494 <= Height_dout;
        VideoFormat_read_reg_478 <= VideoFormat_dout;
        div5_reg_518 <= {{StrideInBytes_dout[15:4]}};
        div_reg_509 <= {{sub_fu_201_p2[15:4]}};
        dstImg2_read_reg_499 <= dstImg2_dout;
        dstImg_read_reg_504 <= dstImg_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        cmp23_reg_529 <= cmp23_fu_243_p2;
        div5_cast_reg_524[11 : 0] <= div5_cast_fu_237_p1[11 : 0];
        icmp_ln1065_reg_538 <= icmp_ln1065_fu_275_p2;
        zext_ln1065_reg_533[15 : 4] <= zext_ln1065_fu_255_p1[15 : 4];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        empty_408_reg_564 <= empty_408_fu_367_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (((empty_408_fu_367_p2 == 1'd1) & (trunc_ln1053_reg_542 == 1'd1)) | ((trunc_ln1053_reg_542 == 1'd1) & (icmp_ln1065_reg_538 == 1'd1))))) begin
        empty_417_reg_568 <= empty_417_fu_416_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        trunc_ln1053_reg_542 <= trunc_ln1053_fu_284_p1;
        y_22_reg_549 <= y_22_fu_293_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (cmp23_reg_529 == 1'd1))) begin
        trunc_ln8_reg_559 <= {{grp_fu_457_p3[31:4]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (((((trunc_ln1053_reg_542 == 1'd0) & (icmp_ln1065_reg_538 == 1'd1) & (cmp23_reg_529 == 1'd1)) | ((empty_417_fu_416_p2 == 1'd0) & (icmp_ln1065_reg_538 == 1'd1) & (cmp23_reg_529 == 1'd1))) | ((empty_417_fu_416_p2 == 1'd0) & (empty_408_fu_367_p2 == 1'd1) & (cmp23_reg_529 == 1'd1))) | ((empty_408_fu_367_p2 == 1'd1) & (trunc_ln1053_reg_542 == 1'd0) & (cmp23_reg_529 == 1'd1))))) begin
        trunc_ln9_reg_572 <= {{add_ln1067_fu_428_p2[31:4]}};
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        Height_blk_n = Height_empty_n;
    end else begin
        Height_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((dstImg_empty_n == 1'b0) | (1'b0 == VideoFormat_empty_n) | (1'b0 == StrideInBytes_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0) | (dstImg2_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        Height_read = 1'b1;
    end else begin
        Height_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        StrideInBytes_blk_n = StrideInBytes_empty_n;
    end else begin
        StrideInBytes_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((dstImg_empty_n == 1'b0) | (1'b0 == VideoFormat_empty_n) | (1'b0 == StrideInBytes_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0) | (dstImg2_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        StrideInBytes_read = 1'b1;
    end else begin
        StrideInBytes_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        VideoFormat_blk_n = VideoFormat_empty_n;
    end else begin
        VideoFormat_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((dstImg_empty_n == 1'b0) | (1'b0 == VideoFormat_empty_n) | (1'b0 == StrideInBytes_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0) | (dstImg2_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        VideoFormat_read = 1'b1;
    end else begin
        VideoFormat_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        WidthInBytes_blk_n = WidthInBytes_empty_n;
    end else begin
        WidthInBytes_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((dstImg_empty_n == 1'b0) | (1'b0 == VideoFormat_empty_n) | (1'b0 == StrideInBytes_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0) | (dstImg2_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        WidthInBytes_read = 1'b1;
    end else begin
        WidthInBytes_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state10_on_subcall_done)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

always @ (*) begin
    if (((dstImg_empty_n == 1'b0) | (1'b0 == VideoFormat_empty_n) | (1'b0 == StrideInBytes_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0) | (dstImg2_empty_n == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln1053_fu_288_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln1053_fu_288_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        bytePlanes_01_read = grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_bytePlanes_01_read;
    end else begin
        bytePlanes_01_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) & (((((empty_417_reg_568 == 1'd0) & (icmp_ln1065_reg_538 == 1'd1) & (cmp23_reg_529 == 1'd1)) | ((trunc_ln1053_reg_542 == 1'd0) & (icmp_ln1065_reg_538 == 1'd1) & (cmp23_reg_529 == 1'd1))) | ((empty_417_reg_568 == 1'd0) & (empty_408_reg_564 == 1'd1) & (cmp23_reg_529 == 1'd1))) | ((empty_408_reg_564 == 1'd1) & (trunc_ln1053_reg_542 == 1'd0) & (cmp23_reg_529 == 1'd1))))) begin
        bytePlanes_12_read = grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_bytePlanes_12_read;
    end else begin
        bytePlanes_12_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        dstImg2_blk_n = dstImg2_empty_n;
    end else begin
        dstImg2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((dstImg_empty_n == 1'b0) | (1'b0 == VideoFormat_empty_n) | (1'b0 == StrideInBytes_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0) | (dstImg2_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        dstImg2_read = 1'b1;
    end else begin
        dstImg2_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        dstImg_blk_n = dstImg_empty_n;
    end else begin
        dstImg_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((dstImg_empty_n == 1'b0) | (1'b0 == VideoFormat_empty_n) | (1'b0 == StrideInBytes_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0) | (dstImg2_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        dstImg_read = 1'b1;
    end else begin
        dstImg_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((1'b1 == ap_CS_fsm_state10) & (((((empty_417_reg_568 == 1'd0) & (icmp_ln1065_reg_538 == 1'd1) & (cmp23_reg_529 == 1'd1)) | ((trunc_ln1053_reg_542 == 1'd0) & (icmp_ln1065_reg_538 == 1'd1) & (cmp23_reg_529 == 1'd1))) | ((empty_417_reg_568 == 1'd0) & (empty_408_reg_564 == 1'd1) & (cmp23_reg_529 == 1'd1))) | ((empty_408_reg_564 == 1'd1) & (trunc_ln1053_reg_542 == 1'd0) & (cmp23_reg_529 == 1'd1)))))) begin
        m_axi_mm_video_AWADDR = grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_AWADDR;
    end else if (((1'b1 == ap_CS_fsm_state7) | ((1'b1 == ap_CS_fsm_state6) & (cmp23_reg_529 == 1'd1)))) begin
        m_axi_mm_video_AWADDR = grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_AWADDR;
    end else begin
        m_axi_mm_video_AWADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((1'b1 == ap_CS_fsm_state10) & (((((empty_417_reg_568 == 1'd0) & (icmp_ln1065_reg_538 == 1'd1) & (cmp23_reg_529 == 1'd1)) | ((trunc_ln1053_reg_542 == 1'd0) & (icmp_ln1065_reg_538 == 1'd1) & (cmp23_reg_529 == 1'd1))) | ((empty_417_reg_568 == 1'd0) & (empty_408_reg_564 == 1'd1) & (cmp23_reg_529 == 1'd1))) | ((empty_408_reg_564 == 1'd1) & (trunc_ln1053_reg_542 == 1'd0) & (cmp23_reg_529 == 1'd1)))))) begin
        m_axi_mm_video_AWBURST = grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_AWBURST;
    end else if (((1'b1 == ap_CS_fsm_state7) | ((1'b1 == ap_CS_fsm_state6) & (cmp23_reg_529 == 1'd1)))) begin
        m_axi_mm_video_AWBURST = grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_AWBURST;
    end else begin
        m_axi_mm_video_AWBURST = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((1'b1 == ap_CS_fsm_state10) & (((((empty_417_reg_568 == 1'd0) & (icmp_ln1065_reg_538 == 1'd1) & (cmp23_reg_529 == 1'd1)) | ((trunc_ln1053_reg_542 == 1'd0) & (icmp_ln1065_reg_538 == 1'd1) & (cmp23_reg_529 == 1'd1))) | ((empty_417_reg_568 == 1'd0) & (empty_408_reg_564 == 1'd1) & (cmp23_reg_529 == 1'd1))) | ((empty_408_reg_564 == 1'd1) & (trunc_ln1053_reg_542 == 1'd0) & (cmp23_reg_529 == 1'd1)))))) begin
        m_axi_mm_video_AWCACHE = grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_AWCACHE;
    end else if (((1'b1 == ap_CS_fsm_state7) | ((1'b1 == ap_CS_fsm_state6) & (cmp23_reg_529 == 1'd1)))) begin
        m_axi_mm_video_AWCACHE = grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_AWCACHE;
    end else begin
        m_axi_mm_video_AWCACHE = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((1'b1 == ap_CS_fsm_state10) & (((((empty_417_reg_568 == 1'd0) & (icmp_ln1065_reg_538 == 1'd1) & (cmp23_reg_529 == 1'd1)) | ((trunc_ln1053_reg_542 == 1'd0) & (icmp_ln1065_reg_538 == 1'd1) & (cmp23_reg_529 == 1'd1))) | ((empty_417_reg_568 == 1'd0) & (empty_408_reg_564 == 1'd1) & (cmp23_reg_529 == 1'd1))) | ((empty_408_reg_564 == 1'd1) & (trunc_ln1053_reg_542 == 1'd0) & (cmp23_reg_529 == 1'd1)))))) begin
        m_axi_mm_video_AWID = grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_AWID;
    end else if (((1'b1 == ap_CS_fsm_state7) | ((1'b1 == ap_CS_fsm_state6) & (cmp23_reg_529 == 1'd1)))) begin
        m_axi_mm_video_AWID = grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_AWID;
    end else begin
        m_axi_mm_video_AWID = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((1'b1 == ap_CS_fsm_state10) & (((((empty_417_reg_568 == 1'd0) & (icmp_ln1065_reg_538 == 1'd1) & (cmp23_reg_529 == 1'd1)) | ((trunc_ln1053_reg_542 == 1'd0) & (icmp_ln1065_reg_538 == 1'd1) & (cmp23_reg_529 == 1'd1))) | ((empty_417_reg_568 == 1'd0) & (empty_408_reg_564 == 1'd1) & (cmp23_reg_529 == 1'd1))) | ((empty_408_reg_564 == 1'd1) & (trunc_ln1053_reg_542 == 1'd0) & (cmp23_reg_529 == 1'd1)))))) begin
        m_axi_mm_video_AWLEN = grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_AWLEN;
    end else if (((1'b1 == ap_CS_fsm_state7) | ((1'b1 == ap_CS_fsm_state6) & (cmp23_reg_529 == 1'd1)))) begin
        m_axi_mm_video_AWLEN = grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_AWLEN;
    end else begin
        m_axi_mm_video_AWLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((1'b1 == ap_CS_fsm_state10) & (((((empty_417_reg_568 == 1'd0) & (icmp_ln1065_reg_538 == 1'd1) & (cmp23_reg_529 == 1'd1)) | ((trunc_ln1053_reg_542 == 1'd0) & (icmp_ln1065_reg_538 == 1'd1) & (cmp23_reg_529 == 1'd1))) | ((empty_417_reg_568 == 1'd0) & (empty_408_reg_564 == 1'd1) & (cmp23_reg_529 == 1'd1))) | ((empty_408_reg_564 == 1'd1) & (trunc_ln1053_reg_542 == 1'd0) & (cmp23_reg_529 == 1'd1)))))) begin
        m_axi_mm_video_AWLOCK = grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_AWLOCK;
    end else if (((1'b1 == ap_CS_fsm_state7) | ((1'b1 == ap_CS_fsm_state6) & (cmp23_reg_529 == 1'd1)))) begin
        m_axi_mm_video_AWLOCK = grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_AWLOCK;
    end else begin
        m_axi_mm_video_AWLOCK = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((1'b1 == ap_CS_fsm_state10) & (((((empty_417_reg_568 == 1'd0) & (icmp_ln1065_reg_538 == 1'd1) & (cmp23_reg_529 == 1'd1)) | ((trunc_ln1053_reg_542 == 1'd0) & (icmp_ln1065_reg_538 == 1'd1) & (cmp23_reg_529 == 1'd1))) | ((empty_417_reg_568 == 1'd0) & (empty_408_reg_564 == 1'd1) & (cmp23_reg_529 == 1'd1))) | ((empty_408_reg_564 == 1'd1) & (trunc_ln1053_reg_542 == 1'd0) & (cmp23_reg_529 == 1'd1)))))) begin
        m_axi_mm_video_AWPROT = grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_AWPROT;
    end else if (((1'b1 == ap_CS_fsm_state7) | ((1'b1 == ap_CS_fsm_state6) & (cmp23_reg_529 == 1'd1)))) begin
        m_axi_mm_video_AWPROT = grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_AWPROT;
    end else begin
        m_axi_mm_video_AWPROT = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((1'b1 == ap_CS_fsm_state10) & (((((empty_417_reg_568 == 1'd0) & (icmp_ln1065_reg_538 == 1'd1) & (cmp23_reg_529 == 1'd1)) | ((trunc_ln1053_reg_542 == 1'd0) & (icmp_ln1065_reg_538 == 1'd1) & (cmp23_reg_529 == 1'd1))) | ((empty_417_reg_568 == 1'd0) & (empty_408_reg_564 == 1'd1) & (cmp23_reg_529 == 1'd1))) | ((empty_408_reg_564 == 1'd1) & (trunc_ln1053_reg_542 == 1'd0) & (cmp23_reg_529 == 1'd1)))))) begin
        m_axi_mm_video_AWQOS = grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_AWQOS;
    end else if (((1'b1 == ap_CS_fsm_state7) | ((1'b1 == ap_CS_fsm_state6) & (cmp23_reg_529 == 1'd1)))) begin
        m_axi_mm_video_AWQOS = grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_AWQOS;
    end else begin
        m_axi_mm_video_AWQOS = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((1'b1 == ap_CS_fsm_state10) & (((((empty_417_reg_568 == 1'd0) & (icmp_ln1065_reg_538 == 1'd1) & (cmp23_reg_529 == 1'd1)) | ((trunc_ln1053_reg_542 == 1'd0) & (icmp_ln1065_reg_538 == 1'd1) & (cmp23_reg_529 == 1'd1))) | ((empty_417_reg_568 == 1'd0) & (empty_408_reg_564 == 1'd1) & (cmp23_reg_529 == 1'd1))) | ((empty_408_reg_564 == 1'd1) & (trunc_ln1053_reg_542 == 1'd0) & (cmp23_reg_529 == 1'd1)))))) begin
        m_axi_mm_video_AWREGION = grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_AWREGION;
    end else if (((1'b1 == ap_CS_fsm_state7) | ((1'b1 == ap_CS_fsm_state6) & (cmp23_reg_529 == 1'd1)))) begin
        m_axi_mm_video_AWREGION = grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_AWREGION;
    end else begin
        m_axi_mm_video_AWREGION = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((1'b1 == ap_CS_fsm_state10) & (((((empty_417_reg_568 == 1'd0) & (icmp_ln1065_reg_538 == 1'd1) & (cmp23_reg_529 == 1'd1)) | ((trunc_ln1053_reg_542 == 1'd0) & (icmp_ln1065_reg_538 == 1'd1) & (cmp23_reg_529 == 1'd1))) | ((empty_417_reg_568 == 1'd0) & (empty_408_reg_564 == 1'd1) & (cmp23_reg_529 == 1'd1))) | ((empty_408_reg_564 == 1'd1) & (trunc_ln1053_reg_542 == 1'd0) & (cmp23_reg_529 == 1'd1)))))) begin
        m_axi_mm_video_AWSIZE = grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_AWSIZE;
    end else if (((1'b1 == ap_CS_fsm_state7) | ((1'b1 == ap_CS_fsm_state6) & (cmp23_reg_529 == 1'd1)))) begin
        m_axi_mm_video_AWSIZE = grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_AWSIZE;
    end else begin
        m_axi_mm_video_AWSIZE = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((1'b1 == ap_CS_fsm_state10) & (((((empty_417_reg_568 == 1'd0) & (icmp_ln1065_reg_538 == 1'd1) & (cmp23_reg_529 == 1'd1)) | ((trunc_ln1053_reg_542 == 1'd0) & (icmp_ln1065_reg_538 == 1'd1) & (cmp23_reg_529 == 1'd1))) | ((empty_417_reg_568 == 1'd0) & (empty_408_reg_564 == 1'd1) & (cmp23_reg_529 == 1'd1))) | ((empty_408_reg_564 == 1'd1) & (trunc_ln1053_reg_542 == 1'd0) & (cmp23_reg_529 == 1'd1)))))) begin
        m_axi_mm_video_AWUSER = grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_AWUSER;
    end else if (((1'b1 == ap_CS_fsm_state7) | ((1'b1 == ap_CS_fsm_state6) & (cmp23_reg_529 == 1'd1)))) begin
        m_axi_mm_video_AWUSER = grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_AWUSER;
    end else begin
        m_axi_mm_video_AWUSER = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((1'b1 == ap_CS_fsm_state10) & (((((empty_417_reg_568 == 1'd0) & (icmp_ln1065_reg_538 == 1'd1) & (cmp23_reg_529 == 1'd1)) | ((trunc_ln1053_reg_542 == 1'd0) & (icmp_ln1065_reg_538 == 1'd1) & (cmp23_reg_529 == 1'd1))) | ((empty_417_reg_568 == 1'd0) & (empty_408_reg_564 == 1'd1) & (cmp23_reg_529 == 1'd1))) | ((empty_408_reg_564 == 1'd1) & (trunc_ln1053_reg_542 == 1'd0) & (cmp23_reg_529 == 1'd1)))))) begin
        m_axi_mm_video_AWVALID = grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_AWVALID;
    end else if (((1'b1 == ap_CS_fsm_state7) | ((1'b1 == ap_CS_fsm_state6) & (cmp23_reg_529 == 1'd1)))) begin
        m_axi_mm_video_AWVALID = grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_AWVALID;
    end else begin
        m_axi_mm_video_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((1'b1 == ap_CS_fsm_state10) & (((((empty_417_reg_568 == 1'd0) & (icmp_ln1065_reg_538 == 1'd1) & (cmp23_reg_529 == 1'd1)) | ((trunc_ln1053_reg_542 == 1'd0) & (icmp_ln1065_reg_538 == 1'd1) & (cmp23_reg_529 == 1'd1))) | ((empty_417_reg_568 == 1'd0) & (empty_408_reg_564 == 1'd1) & (cmp23_reg_529 == 1'd1))) | ((empty_408_reg_564 == 1'd1) & (trunc_ln1053_reg_542 == 1'd0) & (cmp23_reg_529 == 1'd1)))))) begin
        m_axi_mm_video_BREADY = grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_BREADY;
    end else if (((1'b1 == ap_CS_fsm_state7) | ((1'b1 == ap_CS_fsm_state6) & (cmp23_reg_529 == 1'd1)))) begin
        m_axi_mm_video_BREADY = grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_BREADY;
    end else begin
        m_axi_mm_video_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((1'b1 == ap_CS_fsm_state10) & (((((empty_417_reg_568 == 1'd0) & (icmp_ln1065_reg_538 == 1'd1) & (cmp23_reg_529 == 1'd1)) | ((trunc_ln1053_reg_542 == 1'd0) & (icmp_ln1065_reg_538 == 1'd1) & (cmp23_reg_529 == 1'd1))) | ((empty_417_reg_568 == 1'd0) & (empty_408_reg_564 == 1'd1) & (cmp23_reg_529 == 1'd1))) | ((empty_408_reg_564 == 1'd1) & (trunc_ln1053_reg_542 == 1'd0) & (cmp23_reg_529 == 1'd1)))))) begin
        m_axi_mm_video_WDATA = grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_WDATA;
    end else if (((1'b1 == ap_CS_fsm_state7) | ((1'b1 == ap_CS_fsm_state6) & (cmp23_reg_529 == 1'd1)))) begin
        m_axi_mm_video_WDATA = grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_WDATA;
    end else begin
        m_axi_mm_video_WDATA = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((1'b1 == ap_CS_fsm_state10) & (((((empty_417_reg_568 == 1'd0) & (icmp_ln1065_reg_538 == 1'd1) & (cmp23_reg_529 == 1'd1)) | ((trunc_ln1053_reg_542 == 1'd0) & (icmp_ln1065_reg_538 == 1'd1) & (cmp23_reg_529 == 1'd1))) | ((empty_417_reg_568 == 1'd0) & (empty_408_reg_564 == 1'd1) & (cmp23_reg_529 == 1'd1))) | ((empty_408_reg_564 == 1'd1) & (trunc_ln1053_reg_542 == 1'd0) & (cmp23_reg_529 == 1'd1)))))) begin
        m_axi_mm_video_WID = grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_WID;
    end else if (((1'b1 == ap_CS_fsm_state7) | ((1'b1 == ap_CS_fsm_state6) & (cmp23_reg_529 == 1'd1)))) begin
        m_axi_mm_video_WID = grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_WID;
    end else begin
        m_axi_mm_video_WID = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((1'b1 == ap_CS_fsm_state10) & (((((empty_417_reg_568 == 1'd0) & (icmp_ln1065_reg_538 == 1'd1) & (cmp23_reg_529 == 1'd1)) | ((trunc_ln1053_reg_542 == 1'd0) & (icmp_ln1065_reg_538 == 1'd1) & (cmp23_reg_529 == 1'd1))) | ((empty_417_reg_568 == 1'd0) & (empty_408_reg_564 == 1'd1) & (cmp23_reg_529 == 1'd1))) | ((empty_408_reg_564 == 1'd1) & (trunc_ln1053_reg_542 == 1'd0) & (cmp23_reg_529 == 1'd1)))))) begin
        m_axi_mm_video_WLAST = grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_WLAST;
    end else if (((1'b1 == ap_CS_fsm_state7) | ((1'b1 == ap_CS_fsm_state6) & (cmp23_reg_529 == 1'd1)))) begin
        m_axi_mm_video_WLAST = grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_WLAST;
    end else begin
        m_axi_mm_video_WLAST = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((1'b1 == ap_CS_fsm_state10) & (((((empty_417_reg_568 == 1'd0) & (icmp_ln1065_reg_538 == 1'd1) & (cmp23_reg_529 == 1'd1)) | ((trunc_ln1053_reg_542 == 1'd0) & (icmp_ln1065_reg_538 == 1'd1) & (cmp23_reg_529 == 1'd1))) | ((empty_417_reg_568 == 1'd0) & (empty_408_reg_564 == 1'd1) & (cmp23_reg_529 == 1'd1))) | ((empty_408_reg_564 == 1'd1) & (trunc_ln1053_reg_542 == 1'd0) & (cmp23_reg_529 == 1'd1)))))) begin
        m_axi_mm_video_WSTRB = grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_WSTRB;
    end else if (((1'b1 == ap_CS_fsm_state7) | ((1'b1 == ap_CS_fsm_state6) & (cmp23_reg_529 == 1'd1)))) begin
        m_axi_mm_video_WSTRB = grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_WSTRB;
    end else begin
        m_axi_mm_video_WSTRB = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((1'b1 == ap_CS_fsm_state10) & (((((empty_417_reg_568 == 1'd0) & (icmp_ln1065_reg_538 == 1'd1) & (cmp23_reg_529 == 1'd1)) | ((trunc_ln1053_reg_542 == 1'd0) & (icmp_ln1065_reg_538 == 1'd1) & (cmp23_reg_529 == 1'd1))) | ((empty_417_reg_568 == 1'd0) & (empty_408_reg_564 == 1'd1) & (cmp23_reg_529 == 1'd1))) | ((empty_408_reg_564 == 1'd1) & (trunc_ln1053_reg_542 == 1'd0) & (cmp23_reg_529 == 1'd1)))))) begin
        m_axi_mm_video_WUSER = grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_WUSER;
    end else if (((1'b1 == ap_CS_fsm_state7) | ((1'b1 == ap_CS_fsm_state6) & (cmp23_reg_529 == 1'd1)))) begin
        m_axi_mm_video_WUSER = grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_WUSER;
    end else begin
        m_axi_mm_video_WUSER = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((1'b1 == ap_CS_fsm_state10) & (((((empty_417_reg_568 == 1'd0) & (icmp_ln1065_reg_538 == 1'd1) & (cmp23_reg_529 == 1'd1)) | ((trunc_ln1053_reg_542 == 1'd0) & (icmp_ln1065_reg_538 == 1'd1) & (cmp23_reg_529 == 1'd1))) | ((empty_417_reg_568 == 1'd0) & (empty_408_reg_564 == 1'd1) & (cmp23_reg_529 == 1'd1))) | ((empty_408_reg_564 == 1'd1) & (trunc_ln1053_reg_542 == 1'd0) & (cmp23_reg_529 == 1'd1)))))) begin
        m_axi_mm_video_WVALID = grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_m_axi_mm_video_WVALID;
    end else if (((1'b1 == ap_CS_fsm_state7) | ((1'b1 == ap_CS_fsm_state6) & (cmp23_reg_529 == 1'd1)))) begin
        m_axi_mm_video_WVALID = grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_m_axi_mm_video_WVALID;
    end else begin
        m_axi_mm_video_WVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((dstImg_empty_n == 1'b0) | (1'b0 == VideoFormat_empty_n) | (1'b0 == StrideInBytes_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0) | (dstImg2_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln1053_fu_288_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (cmp23_reg_529 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (((((trunc_ln1053_reg_542 == 1'd0) & (icmp_ln1065_reg_538 == 1'd1) & (cmp23_reg_529 == 1'd1)) | ((empty_417_fu_416_p2 == 1'd0) & (icmp_ln1065_reg_538 == 1'd1) & (cmp23_reg_529 == 1'd1))) | ((empty_417_fu_416_p2 == 1'd0) & (empty_408_fu_367_p2 == 1'd1) & (cmp23_reg_529 == 1'd1))) | ((empty_408_fu_367_p2 == 1'd1) & (trunc_ln1053_reg_542 == 1'd0) & (cmp23_reg_529 == 1'd1))))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b0 == ap_block_state10_on_subcall_done) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign VideoFormat_load_cast5_fu_240_p1 = VideoFormat_read_reg_478;

assign WidthInBytes_load_cast_fu_197_p1 = WidthInBytes_dout;

assign add_ln1065_fu_259_p2 = ($signed(VideoFormat_load_cast5_fu_240_p1) + $signed(7'd91));

assign add_ln1067_fu_428_p2 = (dstImg2_read_reg_499 + shl_ln1067_fu_422_p2);

assign and_ln_fu_248_p3 = {{div5_reg_518}, {4'd0}};

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((dstImg_empty_n == 1'b0) | (1'b0 == VideoFormat_empty_n) | (1'b0 == StrideInBytes_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0) | (dstImg2_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state10_on_subcall_done = ((ap_predicate_op98_call_state10 == 1'b1) & (grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_ap_done == 1'b0));
end

always @ (*) begin
    ap_predicate_op98_call_state10 = (((((empty_417_reg_568 == 1'd0) & (icmp_ln1065_reg_538 == 1'd1) & (cmp23_reg_529 == 1'd1)) | ((trunc_ln1053_reg_542 == 1'd0) & (icmp_ln1065_reg_538 == 1'd1) & (cmp23_reg_529 == 1'd1))) | ((empty_417_reg_568 == 1'd0) & (empty_408_reg_564 == 1'd1) & (cmp23_reg_529 == 1'd1))) | ((empty_408_reg_564 == 1'd1) & (trunc_ln1053_reg_542 == 1'd0) & (cmp23_reg_529 == 1'd1)));
end

assign cmp23_fu_243_p2 = ((div_reg_509 != 12'd0) ? 1'b1 : 1'b0);

assign div5_cast_fu_237_p1 = div5_reg_518;

assign empty_398_fu_313_p2 = ((VideoFormat_read_reg_478 == 6'd33) ? 1'b1 : 1'b0);

assign empty_399_fu_318_p2 = ((VideoFormat_read_reg_478 == 6'd32) ? 1'b1 : 1'b0);

assign empty_400_fu_323_p2 = (empty_399_fu_318_p2 | empty_398_fu_313_p2);

assign empty_401_fu_329_p2 = ((VideoFormat_read_reg_478 == 6'd23) ? 1'b1 : 1'b0);

assign empty_402_fu_334_p2 = (empty_401_fu_329_p2 | empty_400_fu_323_p2);

assign empty_403_fu_340_p2 = ((VideoFormat_read_reg_478 == 6'd22) ? 1'b1 : 1'b0);

assign empty_404_fu_345_p2 = (empty_403_fu_340_p2 | empty_402_fu_334_p2);

assign empty_405_fu_351_p2 = ((VideoFormat_read_reg_478 == 6'd19) ? 1'b1 : 1'b0);

assign empty_406_fu_356_p2 = (empty_405_fu_351_p2 | empty_404_fu_345_p2);

assign empty_407_fu_362_p2 = ((VideoFormat_read_reg_478 == 6'd18) ? 1'b1 : 1'b0);

assign empty_408_fu_367_p2 = (empty_407_fu_362_p2 | empty_406_fu_356_p2);

assign empty_409_fu_373_p2 = ((VideoFormat_read_reg_478 == 6'd38) ? 1'b1 : 1'b0);

assign empty_410_fu_378_p2 = ((VideoFormat_read_reg_478 == 6'd33) ? 1'b1 : 1'b0);

assign empty_411_fu_383_p2 = (empty_410_fu_378_p2 | empty_409_fu_373_p2);

assign empty_412_fu_389_p2 = ((VideoFormat_read_reg_478 == 6'd23) ? 1'b1 : 1'b0);

assign empty_413_fu_394_p2 = (empty_412_fu_389_p2 | empty_411_fu_383_p2);

assign empty_414_fu_400_p2 = ((VideoFormat_read_reg_478 == 6'd19) ? 1'b1 : 1'b0);

assign empty_415_fu_405_p2 = (empty_414_fu_400_p2 | empty_413_fu_394_p2);

assign empty_416_fu_411_p2 = ((VideoFormat_read_reg_478 == 6'd3) ? 1'b1 : 1'b0);

assign empty_417_fu_416_p2 = (empty_416_fu_411_p2 | empty_415_fu_405_p2);

assign grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_ap_start = grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1057_1_fu_172_ap_start_reg;

assign grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_ap_start = grp_Bytes2AXIMMvideo_Pipeline_VITIS_LOOP_1067_2_fu_183_ap_start_reg;

assign grp_fu_457_p0 = zext_ln1065_reg_533;

assign grp_fu_457_p1 = grp_fu_457_p10;

assign grp_fu_457_p10 = y_fu_128;

assign icmp_ln1053_fu_288_p2 = ((y_fu_128 == Height_read_reg_494) ? 1'b1 : 1'b0);

assign icmp_ln1065_fu_275_p2 = ((tmp_fu_265_p4 == 6'd0) ? 1'b1 : 1'b0);

assign m_axi_mm_video_ARADDR = 32'd0;

assign m_axi_mm_video_ARBURST = 2'd0;

assign m_axi_mm_video_ARCACHE = 4'd0;

assign m_axi_mm_video_ARID = 1'd0;

assign m_axi_mm_video_ARLEN = 32'd0;

assign m_axi_mm_video_ARLOCK = 2'd0;

assign m_axi_mm_video_ARPROT = 3'd0;

assign m_axi_mm_video_ARQOS = 4'd0;

assign m_axi_mm_video_ARREGION = 4'd0;

assign m_axi_mm_video_ARSIZE = 3'd0;

assign m_axi_mm_video_ARUSER = 1'd0;

assign m_axi_mm_video_ARVALID = 1'b0;

assign m_axi_mm_video_RREADY = 1'b0;

assign offsetUV_1_fu_443_p2 = (offsetUV_fu_132 + div5_cast_reg_524);

assign shl_ln1067_fu_422_p2 = offsetUV_fu_132 << 32'd4;

assign sub_fu_201_p2 = (WidthInBytes_load_cast_fu_197_p1 + 16'd15);

assign tmp_fu_265_p4 = {{add_ln1065_fu_259_p2[6:1]}};

assign trunc_ln1053_fu_284_p1 = y_fu_128[0:0];

assign y_22_fu_293_p2 = (y_fu_128 + 12'd1);

assign zext_ln1065_fu_255_p1 = and_ln_fu_248_p3;

always @ (posedge ap_clk) begin
    div5_cast_reg_524[31:12] <= 20'b00000000000000000000;
    zext_ln1065_reg_533[3:0] <= 4'b0000;
    zext_ln1065_reg_533[27:16] <= 12'b000000000000;
end

endmodule //design_1_v_frmbuf_wr_0_0_Bytes2AXIMMvideo
