// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module design_1_v_tpg_0_0_tpgForeground (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        bckgndYUV_dout,
        bckgndYUV_empty_n,
        bckgndYUV_read,
        height,
        width,
        ovrlayId,
        maskId,
        colorFormat,
        crossHairX,
        crossHairY,
        boxSize,
        boxColorR,
        boxColorG,
        boxColorB,
        motionSpeed,
        ovrlayYUV_din,
        ovrlayYUV_full_n,
        ovrlayYUV_write
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [47:0] bckgndYUV_dout;
input   bckgndYUV_empty_n;
output   bckgndYUV_read;
input  [15:0] height;
input  [15:0] width;
input  [7:0] ovrlayId;
input  [7:0] maskId;
input  [7:0] colorFormat;
input  [15:0] crossHairX;
input  [15:0] crossHairY;
input  [15:0] boxSize;
input  [15:0] boxColorR;
input  [15:0] boxColorG;
input  [15:0] boxColorB;
input  [7:0] motionSpeed;
output  [47:0] ovrlayYUV_din;
input   ovrlayYUV_full_n;
output   ovrlayYUV_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg bckgndYUV_read;
reg ovrlayYUV_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
wire   [1:0] whiYuv_address0;
reg    whiYuv_ce0;
wire   [7:0] whiYuv_q0;
wire    ap_CS_fsm_state2;
wire   [7:0] select_ln1929_fu_298_p3;
reg   [7:0] select_ln1929_reg_426;
reg   [15:0] y_1_reg_431;
wire    ap_CS_fsm_state3;
wire   [0:0] cmp2_i_fu_321_p2;
reg   [0:0] cmp2_i_reg_439;
wire   [0:0] icmp_ln727_fu_310_p2;
wire    grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_175_ap_start;
wire    grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_175_ap_done;
wire    grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_175_ap_idle;
wire    grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_175_ap_ready;
wire    grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_175_bckgndYUV_read;
wire   [47:0] grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_175_ovrlayYUV_din;
wire    grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_175_ovrlayYUV_write;
wire   [0:0] grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_175_and4_i;
wire   [0:0] grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_175_and24_i;
wire   [0:0] grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_175_tobool;
wire   [0:0] grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_175_and10_i;
wire   [7:0] grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_175_boxColorR_load_cast;
wire   [7:0] grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_175_boxColorG_load_cast;
wire   [7:0] grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_175_boxColorB_load_cast;
wire   [7:0] grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_175_conv_i_i;
reg    grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_175_ap_start_reg;
wire    ap_CS_fsm_state4;
wire   [63:0] idxprom18_1_i_cast_cast_cast_fu_215_p3;
reg   [15:0] y_fu_86;
wire   [15:0] y_2_fu_315_p2;
reg    ap_block_state1;
wire   [0:0] cmp13_i_fu_209_p2;
wire   [0:0] cmp11_i_fu_247_p2;
wire   [0:0] empty_72_fu_260_p1;
wire   [0:0] tmp_fu_270_p3;
wire   [0:0] tmp_2_fu_284_p3;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_175_ap_start_reg = 1'b0;
end

design_1_v_tpg_0_0_tpgForeground_whiYuv_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
whiYuv_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(whiYuv_address0),
    .ce0(whiYuv_ce0),
    .q0(whiYuv_q0)
);

design_1_v_tpg_0_0_tpgForeground_Pipeline_VITIS_LOOP_729_2 grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_175(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_175_ap_start),
    .ap_done(grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_175_ap_done),
    .ap_idle(grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_175_ap_idle),
    .ap_ready(grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_175_ap_ready),
    .bckgndYUV_dout(bckgndYUV_dout),
    .bckgndYUV_empty_n(bckgndYUV_empty_n),
    .bckgndYUV_read(grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_175_bckgndYUV_read),
    .ovrlayYUV_din(grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_175_ovrlayYUV_din),
    .ovrlayYUV_full_n(ovrlayYUV_full_n),
    .ovrlayYUV_write(grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_175_ovrlayYUV_write),
    .loopWidth(width),
    .and4_i(grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_175_and4_i),
    .and24_i(grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_175_and24_i),
    .tobool(grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_175_tobool),
    .and10_i(grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_175_and10_i),
    .ovrlayId_load(ovrlayId),
    .y(y_1_reg_431),
    .loopHeight(height),
    .boxSize_load(boxSize),
    .boxColorR_load_cast(grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_175_boxColorR_load_cast),
    .boxColorG_load_cast(grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_175_boxColorG_load_cast),
    .boxColorB_load_cast(grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_175_boxColorB_load_cast),
    .motionSpeed_load(motionSpeed),
    .color(colorFormat),
    .crossHairX_1(crossHairX),
    .cmp2_i(cmp2_i_reg_439),
    .conv_i_i(grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_175_conv_i_i),
    .select_ln1929(select_ln1929_reg_426)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln727_fu_310_p2 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_175_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln727_fu_310_p2 == 1'd0))) begin
            grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_175_ap_start_reg <= 1'b1;
        end else if ((grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_175_ap_ready == 1'b1)) begin
            grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_175_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        y_fu_86 <= 16'd0;
    end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln727_fu_310_p2 == 1'd0))) begin
        y_fu_86 <= y_2_fu_315_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln727_fu_310_p2 == 1'd0))) begin
        cmp2_i_reg_439 <= cmp2_i_fu_321_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        select_ln1929_reg_426 <= select_ln1929_fu_298_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        y_1_reg_431 <= y_fu_86;
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (real_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_175_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln727_fu_310_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        bckgndYUV_read = grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_175_bckgndYUV_read;
    end else begin
        bckgndYUV_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln727_fu_310_p2 == 1'd1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ovrlayYUV_write = grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_175_ovrlayYUV_write;
    end else begin
        ovrlayYUV_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        whiYuv_ce0 = 1'b1;
    end else begin
        whiYuv_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln727_fu_310_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_175_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign cmp11_i_fu_247_p2 = ((colorFormat == 8'd0) ? 1'b1 : 1'b0);

assign cmp13_i_fu_209_p2 = ((colorFormat == 8'd1) ? 1'b1 : 1'b0);

assign cmp2_i_fu_321_p2 = ((y_fu_86 == crossHairY) ? 1'b1 : 1'b0);

assign empty_72_fu_260_p1 = maskId[0:0];

assign grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_175_and10_i = (tmp_fu_270_p3 & cmp11_i_fu_247_p2);

assign grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_175_and24_i = (tmp_2_fu_284_p3 & cmp11_i_fu_247_p2);

assign grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_175_and4_i = (empty_72_fu_260_p1 & cmp11_i_fu_247_p2);

assign grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_175_ap_start = grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_175_ap_start_reg;

assign grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_175_boxColorB_load_cast = boxColorB[7:0];

assign grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_175_boxColorG_load_cast = boxColorG[7:0];

assign grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_175_boxColorR_load_cast = boxColorR[7:0];

assign grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_175_conv_i_i = ((cmp11_i_fu_247_p2[0:0] == 1'b1) ? 8'd240 : 8'd128);

assign grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_175_tobool = ((maskId == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln727_fu_310_p2 = ((y_fu_86 == height) ? 1'b1 : 1'b0);

assign idxprom18_1_i_cast_cast_cast_fu_215_p3 = ((cmp13_i_fu_209_p2[0:0] == 1'b1) ? 64'd1 : 64'd2);

assign ovrlayYUV_din = grp_tpgForeground_Pipeline_VITIS_LOOP_729_2_fu_175_ovrlayYUV_din;

assign select_ln1929_fu_298_p3 = ((cmp11_i_fu_247_p2[0:0] == 1'b1) ? 8'd240 : whiYuv_q0);

assign start_out = real_start;

assign tmp_2_fu_284_p3 = maskId[32'd2];

assign tmp_fu_270_p3 = maskId[32'd1];

assign whiYuv_address0 = idxprom18_1_i_cast_cast_cast_fu_215_p3;

assign y_2_fu_315_p2 = (y_fu_86 + 16'd1);

endmodule //design_1_v_tpg_0_0_tpgForeground
