// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module design_1_v_tpg_0_0_MultiPixStream2AXIvideo (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        ovrlayYUV_dout,
        ovrlayYUV_empty_n,
        ovrlayYUV_read,
        m_axis_video_TDATA,
        m_axis_video_TVALID,
        m_axis_video_TREADY,
        m_axis_video_TKEEP,
        m_axis_video_TSTRB,
        m_axis_video_TUSER,
        m_axis_video_TLAST,
        m_axis_video_TID,
        m_axis_video_TDEST,
        height,
        width,
        colorFormat,
        fid_in,
        fid,
        fid_ap_vld,
        field_id
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [47:0] ovrlayYUV_dout;
input   ovrlayYUV_empty_n;
output   ovrlayYUV_read;
output  [47:0] m_axis_video_TDATA;
output   m_axis_video_TVALID;
input   m_axis_video_TREADY;
output  [5:0] m_axis_video_TKEEP;
output  [5:0] m_axis_video_TSTRB;
output  [0:0] m_axis_video_TUSER;
output  [0:0] m_axis_video_TLAST;
output  [0:0] m_axis_video_TID;
output  [0:0] m_axis_video_TDEST;
input  [15:0] height;
input  [15:0] width;
input  [7:0] colorFormat;
input  [0:0] fid_in;
output  [0:0] fid;
output   fid_ap_vld;
input  [15:0] field_id;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg ovrlayYUV_read;
reg[0:0] fid;
reg fid_ap_vld;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [0:0] fidStored;
reg   [15:0] counter;
wire   [11:0] trunc_ln882_fu_186_p1;
wire   [10:0] div_fu_194_p4;
wire   [0:0] cmp92_fu_214_p2;
wire   [0:0] cmp30209_fu_220_p2;
wire   [0:0] switch_le_fu_232_p2;
wire   [0:0] icmp_ln993_fu_238_p2;
wire   [0:0] icmp_ln993_1_fu_244_p2;
wire   [11:0] i_2_fu_294_p2;
reg   [11:0] i_2_reg_450;
wire    ap_CS_fsm_state2;
wire    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_ap_start;
wire    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_ap_done;
wire    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_ap_idle;
wire    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_ap_ready;
wire   [10:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_div;
wire    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_ovrlayYUV_read;
wire   [0:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_icmp_ln975;
wire   [0:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_icmp_ln975_1;
wire   [47:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_m_axis_video_TDATA;
wire    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_m_axis_video_TVALID;
wire    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_m_axis_video_TREADY;
wire   [5:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_m_axis_video_TKEEP;
wire   [5:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_m_axis_video_TSTRB;
wire   [0:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_m_axis_video_TUSER;
wire   [0:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_m_axis_video_TLAST;
wire   [0:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_m_axis_video_TID;
wire   [0:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_m_axis_video_TDEST;
wire   [11:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_sub;
wire   [15:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_counter_loc_1_out_o;
wire    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_counter_loc_1_out_o_ap_vld;
wire   [0:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_phi_ln991_out;
wire    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_phi_ln991_out_ap_vld;
wire   [15:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_counter;
wire    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_counter_ap_vld;
reg    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_ap_start_reg;
wire   [0:0] icmp_ln934_fu_289_p2;
wire    ap_CS_fsm_state3;
reg   [15:0] counter_loc_0_fu_112;
reg   [0:0] phi_ln991_loc_fu_116;
reg   [11:0] i_fu_100;
wire    ap_CS_fsm_state4;
reg    ap_block_state1;
reg   [0:0] empty_fu_104;
wire   [0:0] select_ln993_fu_339_p3;
reg   [0:0] sof_fu_108;
reg   [0:0] fid_preg;
wire   [11:0] div_cast_fu_204_p1;
wire   [15:0] empty_189_fu_226_p2;
wire   [0:0] and_ln993_fu_317_p2;
wire   [0:0] xor_ln1008_fu_327_p2;
wire   [0:0] or_ln993_fu_322_p2;
wire   [0:0] select_ln1006_fu_333_p3;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 fidStored = 1'd0;
#0 counter = 16'd0;
#0 grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_ap_start_reg = 1'b0;
#0 fid_preg = 1'd0;
end

design_1_v_tpg_0_0_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2 grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_ap_start),
    .ap_done(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_ap_done),
    .ap_idle(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_ap_idle),
    .ap_ready(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_ap_ready),
    .sof(sof_fu_108),
    .div(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_div),
    .ovrlayYUV_dout(ovrlayYUV_dout),
    .ovrlayYUV_empty_n(ovrlayYUV_empty_n),
    .ovrlayYUV_read(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_ovrlayYUV_read),
    .icmp_ln975(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_icmp_ln975),
    .icmp_ln975_1(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_icmp_ln975_1),
    .m_axis_video_TDATA(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_m_axis_video_TDATA),
    .m_axis_video_TVALID(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_m_axis_video_TVALID),
    .m_axis_video_TREADY(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_m_axis_video_TREADY),
    .m_axis_video_TKEEP(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_m_axis_video_TKEEP),
    .m_axis_video_TSTRB(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_m_axis_video_TSTRB),
    .m_axis_video_TUSER(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_m_axis_video_TUSER),
    .m_axis_video_TLAST(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_m_axis_video_TLAST),
    .m_axis_video_TID(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_m_axis_video_TID),
    .m_axis_video_TDEST(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_m_axis_video_TDEST),
    .sub(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_sub),
    .counter_loc_1_out_i(counter_loc_0_fu_112),
    .counter_loc_1_out_o(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_counter_loc_1_out_o),
    .counter_loc_1_out_o_ap_vld(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_counter_loc_1_out_o_ap_vld),
    .phi_ln991_out(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_phi_ln991_out),
    .phi_ln991_out_ap_vld(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_phi_ln991_out_ap_vld),
    .counter(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_counter),
    .counter_ap_vld(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_counter_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln934_fu_289_p2 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        fid_preg <= 1'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln934_fu_289_p2 == 1'd1))) begin
            fid_preg <= empty_fu_104;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_ap_start_reg <= 1'b0;
    end else begin
        if (((cmp30209_fu_220_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln934_fu_289_p2 == 1'd0))) begin
            grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_ap_start_reg <= 1'b1;
        end else if ((grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_ap_ready == 1'b1)) begin
            grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        counter_loc_0_fu_112 <= counter;
    end else if (((1'b1 == ap_CS_fsm_state3) & (grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_counter_loc_1_out_o_ap_vld == 1'b1))) begin
        counter_loc_0_fu_112 <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_counter_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        empty_fu_104 <= fidStored;
    end else if (((cmp30209_fu_220_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        empty_fu_104 <= select_ln993_fu_339_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_fu_100 <= 12'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        i_fu_100 <= i_2_reg_450;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        sof_fu_108 <= 1'd1;
    end else if (((cmp30209_fu_220_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        sof_fu_108 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_counter_ap_vld == 1'b1))) begin
        counter <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_counter;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln934_fu_289_p2 == 1'd1))) begin
        fidStored <= empty_fu_104;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_2_reg_450 <= i_2_fu_294_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_phi_ln991_out_ap_vld == 1'b1))) begin
        phi_ln991_loc_fu_116 <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_phi_ln991_out;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln934_fu_289_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln934_fu_289_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln934_fu_289_p2 == 1'd1))) begin
        fid = empty_fu_104;
    end else begin
        fid = fid_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln934_fu_289_p2 == 1'd1))) begin
        fid_ap_vld = 1'b1;
    end else begin
        fid_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        ovrlayYUV_read = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_ovrlayYUV_read;
    end else begin
        ovrlayYUV_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln934_fu_289_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((cmp30209_fu_220_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln934_fu_289_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign and_ln993_fu_317_p2 = (phi_ln991_loc_fu_116 & icmp_ln993_fu_238_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign cmp30209_fu_220_p2 = ((div_fu_194_p4 == 11'd0) ? 1'b1 : 1'b0);

assign cmp92_fu_214_p2 = ((field_id == 16'd3) ? 1'b1 : 1'b0);

assign div_cast_fu_204_p1 = div_fu_194_p4;

assign div_fu_194_p4 = {{width[11:1]}};

assign empty_189_fu_226_p2 = (field_id | 16'd1);

assign grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_ap_start = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_ap_start_reg;

assign grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_div = {{width[11:1]}};

assign grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_icmp_ln975 = ((colorFormat == 8'd1) ? 1'b1 : 1'b0);

assign grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_icmp_ln975_1 = ((colorFormat == 8'd0) ? 1'b1 : 1'b0);

assign grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_m_axis_video_TREADY = (m_axis_video_TREADY & ap_CS_fsm_state3);

assign grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_sub = ($signed(div_cast_fu_204_p1) + $signed(12'd4095));

assign i_2_fu_294_p2 = (i_fu_100 + 12'd1);

assign icmp_ln934_fu_289_p2 = ((i_fu_100 == trunc_ln882_fu_186_p1) ? 1'b1 : 1'b0);

assign icmp_ln993_1_fu_244_p2 = ((empty_189_fu_226_p2 != 16'd1) ? 1'b1 : 1'b0);

assign icmp_ln993_fu_238_p2 = ((field_id != 16'd0) ? 1'b1 : 1'b0);

assign m_axis_video_TDATA = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_m_axis_video_TDATA;

assign m_axis_video_TDEST = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_m_axis_video_TDEST;

assign m_axis_video_TID = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_m_axis_video_TID;

assign m_axis_video_TKEEP = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_m_axis_video_TKEEP;

assign m_axis_video_TLAST = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_m_axis_video_TLAST;

assign m_axis_video_TSTRB = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_m_axis_video_TSTRB;

assign m_axis_video_TUSER = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_m_axis_video_TUSER;

assign m_axis_video_TVALID = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_157_m_axis_video_TVALID;

assign or_ln993_fu_322_p2 = (icmp_ln993_1_fu_244_p2 | and_ln993_fu_317_p2);

assign select_ln1006_fu_333_p3 = ((cmp92_fu_214_p2[0:0] == 1'b1) ? xor_ln1008_fu_327_p2 : fid_in);

assign select_ln993_fu_339_p3 = ((switch_le_fu_232_p2[0:0] == 1'b1) ? or_ln993_fu_322_p2 : select_ln1006_fu_333_p3);

assign switch_le_fu_232_p2 = ((field_id < 16'd3) ? 1'b1 : 1'b0);

assign trunc_ln882_fu_186_p1 = height[11:0];

assign xor_ln1008_fu_327_p2 = (phi_ln991_loc_fu_116 ^ 1'd1);

endmodule //design_1_v_tpg_0_0_MultiPixStream2AXIvideo
