// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module design_1_v_tpg_0_0_tpgBackground (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        srcYUV_dout,
        srcYUV_empty_n,
        srcYUV_read,
        height,
        width,
        passthruStartX,
        passthruStartY,
        passthruEndX,
        passthruEndY,
        enableInput,
        bckgndId,
        ZplateHorContStart,
        ZplateHorContDelta,
        ZplateVerContStart,
        ZplateVerContDelta,
        dpYUVCoef,
        motionSpeed,
        bckgndYUV_din,
        bckgndYUV_full_n,
        bckgndYUV_write,
        s
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [47:0] srcYUV_dout;
input   srcYUV_empty_n;
output   srcYUV_read;
input  [15:0] height;
input  [15:0] width;
input  [15:0] passthruStartX;
input  [15:0] passthruStartY;
input  [15:0] passthruEndX;
input  [15:0] passthruEndY;
input  [7:0] enableInput;
input  [7:0] bckgndId;
input  [15:0] ZplateHorContStart;
input  [15:0] ZplateHorContDelta;
input  [15:0] ZplateVerContStart;
input  [15:0] ZplateVerContDelta;
input  [7:0] dpYUVCoef;
input  [7:0] motionSpeed;
output  [47:0] bckgndYUV_din;
input   bckgndYUV_full_n;
output   bckgndYUV_write;
input  [31:0] s;

reg ap_done;
reg ap_idle;
reg start_write;
reg srcYUV_read;
reg bckgndYUV_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg   [7:0] rampStart;
reg   [15:0] rampVal_1;
reg   [7:0] rampVal;
reg   [7:0] hBarSel_0_2;
reg   [10:0] xBar_V_1;
reg   [10:0] xBar_V;
reg   [7:0] hBarSel_1_2;
reg   [15:0] zonePlateVAddr;
reg   [15:0] zonePlateVDelta;
reg   [15:0] hdata;
reg   [15:0] rampVal_2;
wire   [13:0] trunc_ln506_fu_627_p1;
reg   [7:0] rampStart_load_reg_1167;
wire   [15:0] shl_ln_fu_701_p3;
reg   [15:0] shl_ln_reg_1174;
reg   [15:0] y_3_reg_1179;
wire    ap_CS_fsm_state2;
wire   [7:0] trunc_ln518_fu_767_p1;
reg   [7:0] trunc_ln518_reg_1186;
reg   [7:0] outpix_val_V_load_reg_1194;
wire   [0:0] icmp_ln518_fu_771_p2;
reg   [7:0] outpix_val_V_1_load_reg_1199;
reg   [7:0] outpix_val_V_2_load_reg_1204;
reg   [7:0] outpix_val_V_3_load_reg_1209;
reg   [7:0] outpix_val_V_4_load_reg_1214;
reg   [7:0] outpix_val_V_5_load_reg_1219;
wire   [0:0] cmp35_not_fu_800_p2;
reg   [0:0] cmp35_not_reg_1224;
wire   [0:0] ult_fu_805_p2;
reg   [0:0] ult_reg_1229;
wire   [0:0] rev102_fu_853_p2;
reg   [0:0] rev102_reg_1234;
wire    ap_CS_fsm_state3;
wire   [0:0] cmp11_i_fu_859_p2;
reg   [0:0] cmp11_i_reg_1239;
wire   [7:0] add_ln1488_fu_874_p2;
reg   [7:0] add_ln1488_reg_1244;
wire   [0:0] icmp_ln1592_fu_879_p2;
reg   [0:0] icmp_ln1592_reg_1249;
wire   [0:0] icmp_ln1592_1_fu_886_p2;
reg   [0:0] icmp_ln1592_1_reg_1254;
wire   [0:0] or_ln1592_fu_893_p2;
reg   [0:0] or_ln1592_reg_1259;
wire   [0:0] icmp_ln1592_2_fu_900_p2;
reg   [0:0] icmp_ln1592_2_reg_1264;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_ap_start;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_ap_done;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_ap_idle;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_ap_ready;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_srcYUV_read;
wire   [47:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_bckgndYUV_din;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_bckgndYUV_write;
wire   [0:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_cmp6;
wire   [10:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_barWidth;
wire   [10:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_barWidth_cast;
wire   [13:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_trunc_ln;
wire   [0:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_3_flag_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_3_flag_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_3_new_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_3_new_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_3_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_3_loc_1_out_o_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_0_4_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_0_4_loc_1_out_o_ap_vld;
wire   [10:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_lhs_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_lhs_out_o_ap_vld;
wire   [10:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_lhs_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_lhs_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_1_4_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_1_4_loc_1_out_o_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_zonePlateVAddr_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_zonePlateVAddr_loc_1_out_o_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_zonePlateVDelta_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_zonePlateVDelta_loc_1_out_o_ap_vld;
wire   [0:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hdata_flag_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hdata_flag_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hdata_new_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hdata_new_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hdata_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hdata_loc_1_out_o_ap_vld;
wire   [0:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_2_flag_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_2_flag_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_2_new_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_2_new_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_2_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_2_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_outpix_val_V_11_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_outpix_val_V_11_out_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_outpix_val_V_10_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_outpix_val_V_10_out_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_outpix_val_V_9_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_outpix_val_V_9_out_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_outpix_val_V_8_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_outpix_val_V_8_out_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_outpix_val_V_7_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_outpix_val_V_7_out_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_outpix_val_V_6_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_outpix_val_V_6_out_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_5_0_0_0252382_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_5_0_0_0252382_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_4_0_0_0250380_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_4_0_0_0250380_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_3_0_0_0248378_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_3_0_0_0248378_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_2_0_0_0246376_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_2_0_0_0246376_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_1_0_0_0244374_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_1_0_0_0244374_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_0_0_0_0242372_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_0_0_0_0242372_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_ap_vld;
wire   [10:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_xBar_V;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_xBar_V_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_1_2;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_1_2_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_0_2;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_0_2_ap_vld;
wire   [10:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_xBar_V_1;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_xBar_V_1_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_zonePlateVAddr;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_zonePlateVAddr_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_zonePlateVDelta;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_zonePlateVDelta_ap_vld;
wire   [0:0] ap_phi_mux_rampVal_3_flag_0_phi_fu_410_p4;
reg   [0:0] rampVal_3_flag_0_reg_406;
reg    ap_block_state1;
wire    ap_CS_fsm_state5;
wire   [0:0] ap_phi_mux_hdata_flag_0_phi_fu_422_p4;
reg   [0:0] hdata_flag_0_reg_418;
wire   [0:0] ap_phi_mux_rampVal_2_flag_0_phi_fu_434_p4;
reg   [0:0] rampVal_2_flag_0_reg_430;
reg    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_ap_start_reg;
wire    ap_CS_fsm_state4;
reg   [15:0] rampVal_3_new_0_fu_306;
reg   [15:0] rampVal_3_loc_0_fu_302;
reg   [15:0] rampVal_loc_0_fu_298;
reg   [7:0] hBarSel_0_4_loc_0_fu_294;
reg   [10:0] xBar_V_1_loc_0_fu_290;
reg   [10:0] xBar_V_loc_0_fu_286;
reg   [7:0] hBarSel_1_4_loc_0_fu_282;
reg   [15:0] zonePlateVAddr_loc_0_fu_278;
reg   [15:0] zonePlateVDelta_loc_0_fu_274;
reg   [15:0] hdata_new_0_fu_270;
reg   [15:0] hdata_loc_0_fu_266;
reg   [15:0] rampVal_2_new_0_fu_262;
reg   [15:0] rampVal_2_loc_0_fu_258;
reg   [7:0] outpix_val_V_5_fu_254;
reg   [7:0] outpix_val_V_4_fu_250;
reg   [7:0] outpix_val_V_3_fu_246;
reg   [7:0] outpix_val_V_2_fu_242;
reg   [7:0] outpix_val_V_1_fu_238;
reg   [7:0] outpix_val_V_fu_234;
reg   [7:0] p_0_5_0_0_0252383_lcssa401_fu_230;
reg   [7:0] p_0_4_0_0_0250381_lcssa398_fu_226;
reg   [7:0] p_0_3_0_0_0248379_lcssa395_fu_222;
reg   [7:0] p_0_2_0_0_0246377_lcssa392_fu_218;
reg   [7:0] p_0_1_0_0_0244375_lcssa389_fu_214;
reg   [7:0] p_0_0_0_0_0242373_lcssa386_fu_210;
wire   [7:0] add_ln705_fu_815_p2;
reg   [15:0] y_fu_206;
wire   [15:0] y_4_fu_776_p2;
wire   [15:0] zext_ln1212_fu_665_p1;
wire   [13:0] add_i_fu_637_p2;
wire   [1:0] Sel_fu_865_p4;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 5'd1;
#0 rampStart = 8'd0;
#0 rampVal_1 = 16'd0;
#0 rampVal = 8'd0;
#0 hBarSel_0_2 = 8'd0;
#0 xBar_V_1 = 11'd0;
#0 xBar_V = 11'd0;
#0 hBarSel_1_2 = 8'd0;
#0 zonePlateVAddr = 16'd0;
#0 zonePlateVDelta = 16'd0;
#0 hdata = 16'd0;
#0 rampVal_2 = 16'd0;
#0 grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_ap_start_reg = 1'b0;
end

design_1_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_520_2 grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_ap_start),
    .ap_done(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_ap_done),
    .ap_idle(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_ap_idle),
    .ap_ready(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_ap_ready),
    .srcYUV_dout(srcYUV_dout),
    .srcYUV_empty_n(srcYUV_empty_n),
    .srcYUV_read(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_srcYUV_read),
    .bckgndYUV_din(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_bckgndYUV_din),
    .bckgndYUV_full_n(bckgndYUV_full_n),
    .bckgndYUV_write(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_bckgndYUV_write),
    .rampVal_3_flag_0(rampVal_3_flag_0_reg_406),
    .hdata_flag_0(hdata_flag_0_reg_418),
    .rampVal_2_flag_0(rampVal_2_flag_0_reg_430),
    .outpix_val_V_5(outpix_val_V_5_load_reg_1219),
    .outpix_val_V_4(outpix_val_V_4_load_reg_1214),
    .outpix_val_V_3(outpix_val_V_3_load_reg_1209),
    .outpix_val_V_2(outpix_val_V_2_load_reg_1204),
    .outpix_val_V_1(outpix_val_V_1_load_reg_1199),
    .outpix_val_V(outpix_val_V_load_reg_1194),
    .loopWidth(width),
    .rampStart_1(rampStart_load_reg_1167),
    .cmp6(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_cmp6),
    .bckgndId_load(bckgndId),
    .zext_ln1032(rampStart_load_reg_1167),
    .y(y_3_reg_1179),
    .barWidth(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_barWidth),
    .barWidth_cast(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_barWidth_cast),
    .shl_ln(shl_ln_reg_1174),
    .Zplate_Ver_Control_Start(ZplateVerContStart),
    .Zplate_Hor_Control_Start(ZplateHorContStart),
    .Zplate_Hor_Control_Delta(ZplateHorContDelta),
    .cmp11_i(cmp11_i_reg_1239),
    .Zplate_Ver_Control_Delta(ZplateVerContDelta),
    .trunc_ln3(trunc_ln506_fu_627_p1),
    .trunc_ln(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_trunc_ln),
    .loopHeight(height),
    .add_ln1488(add_ln1488_reg_1244),
    .or_ln1592(or_ln1592_reg_1259),
    .icmp_ln1592_2(icmp_ln1592_2_reg_1264),
    .icmp_ln1592(icmp_ln1592_reg_1249),
    .icmp_ln1592_1(icmp_ln1592_1_reg_1254),
    .dpYUVCoef_load(dpYUVCoef),
    .passthruStartX_load(passthruStartX),
    .passthruEndX_load(passthruEndX),
    .cmp35_not(cmp35_not_reg_1224),
    .cmp42_not(rev102_reg_1234),
    .rampVal_3_flag_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_3_flag_1_out),
    .rampVal_3_flag_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_3_flag_1_out_ap_vld),
    .rampVal_3_new_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_3_new_1_out),
    .rampVal_3_new_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_3_new_1_out_ap_vld),
    .rampVal_3_loc_1_out_i(rampVal_3_loc_0_fu_302),
    .rampVal_3_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_3_loc_1_out_o),
    .rampVal_3_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_3_loc_1_out_o_ap_vld),
    .rampVal_loc_1_out_i(rampVal_loc_0_fu_298),
    .rampVal_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_loc_1_out_o),
    .rampVal_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_loc_1_out_o_ap_vld),
    .hBarSel_0_4_loc_1_out_i(hBarSel_0_4_loc_0_fu_294),
    .hBarSel_0_4_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_0_4_loc_1_out_o),
    .hBarSel_0_4_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_0_4_loc_1_out_o_ap_vld),
    .lhs_out_i(xBar_V_1_loc_0_fu_290),
    .lhs_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_lhs_out_o),
    .lhs_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_lhs_out_o_ap_vld),
    .lhs_1_out_i(xBar_V_loc_0_fu_286),
    .lhs_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_lhs_1_out_o),
    .lhs_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_lhs_1_out_o_ap_vld),
    .hBarSel_1_4_loc_1_out_i(hBarSel_1_4_loc_0_fu_282),
    .hBarSel_1_4_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_1_4_loc_1_out_o),
    .hBarSel_1_4_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_1_4_loc_1_out_o_ap_vld),
    .zonePlateVAddr_loc_1_out_i(zonePlateVAddr_loc_0_fu_278),
    .zonePlateVAddr_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_zonePlateVAddr_loc_1_out_o),
    .zonePlateVAddr_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_zonePlateVAddr_loc_1_out_o_ap_vld),
    .zonePlateVDelta_loc_1_out_i(zonePlateVDelta_loc_0_fu_274),
    .zonePlateVDelta_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_zonePlateVDelta_loc_1_out_o),
    .zonePlateVDelta_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_zonePlateVDelta_loc_1_out_o_ap_vld),
    .hdata_flag_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hdata_flag_1_out),
    .hdata_flag_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hdata_flag_1_out_ap_vld),
    .hdata_new_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hdata_new_1_out),
    .hdata_new_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hdata_new_1_out_ap_vld),
    .hdata_loc_1_out_i(hdata_loc_0_fu_266),
    .hdata_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hdata_loc_1_out_o),
    .hdata_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hdata_loc_1_out_o_ap_vld),
    .rampVal_2_flag_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_2_flag_1_out),
    .rampVal_2_flag_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_2_flag_1_out_ap_vld),
    .rampVal_2_new_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_2_new_1_out),
    .rampVal_2_new_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_2_new_1_out_ap_vld),
    .rampVal_2_loc_1_out_i(rampVal_2_loc_0_fu_258),
    .rampVal_2_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_2_loc_1_out_o),
    .rampVal_2_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_2_loc_1_out_o_ap_vld),
    .outpix_val_V_11_out(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_outpix_val_V_11_out),
    .outpix_val_V_11_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_outpix_val_V_11_out_ap_vld),
    .outpix_val_V_10_out(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_outpix_val_V_10_out),
    .outpix_val_V_10_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_outpix_val_V_10_out_ap_vld),
    .outpix_val_V_9_out(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_outpix_val_V_9_out),
    .outpix_val_V_9_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_outpix_val_V_9_out_ap_vld),
    .outpix_val_V_8_out(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_outpix_val_V_8_out),
    .outpix_val_V_8_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_outpix_val_V_8_out_ap_vld),
    .outpix_val_V_7_out(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_outpix_val_V_7_out),
    .outpix_val_V_7_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_outpix_val_V_7_out_ap_vld),
    .outpix_val_V_6_out(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_outpix_val_V_6_out),
    .outpix_val_V_6_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_outpix_val_V_6_out_ap_vld),
    .p_0_5_0_0_0252382_out_i(p_0_5_0_0_0252383_lcssa401_fu_230),
    .p_0_5_0_0_0252382_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_5_0_0_0252382_out_o),
    .p_0_5_0_0_0252382_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_5_0_0_0252382_out_o_ap_vld),
    .p_0_4_0_0_0250380_out_i(p_0_4_0_0_0250381_lcssa398_fu_226),
    .p_0_4_0_0_0250380_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_4_0_0_0250380_out_o),
    .p_0_4_0_0_0250380_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_4_0_0_0250380_out_o_ap_vld),
    .p_0_3_0_0_0248378_out_i(p_0_3_0_0_0248379_lcssa395_fu_222),
    .p_0_3_0_0_0248378_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_3_0_0_0248378_out_o),
    .p_0_3_0_0_0248378_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_3_0_0_0248378_out_o_ap_vld),
    .p_0_2_0_0_0246376_out_i(p_0_2_0_0_0246377_lcssa392_fu_218),
    .p_0_2_0_0_0246376_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_2_0_0_0246376_out_o),
    .p_0_2_0_0_0246376_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_2_0_0_0246376_out_o_ap_vld),
    .p_0_1_0_0_0244374_out_i(p_0_1_0_0_0244375_lcssa389_fu_214),
    .p_0_1_0_0_0244374_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_1_0_0_0244374_out_o),
    .p_0_1_0_0_0244374_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_1_0_0_0244374_out_o_ap_vld),
    .p_0_0_0_0_0242372_out_i(p_0_0_0_0_0242373_lcssa386_fu_210),
    .p_0_0_0_0_0242372_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_0_0_0_0242372_out_o),
    .p_0_0_0_0_0242372_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_0_0_0_0242372_out_o_ap_vld),
    .rampVal(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal),
    .rampVal_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_ap_vld),
    .xBar_V(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_xBar_V),
    .xBar_V_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_xBar_V_ap_vld),
    .hBarSel_1_2(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_1_2),
    .hBarSel_1_2_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_1_2_ap_vld),
    .hBarSel_0_2(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_0_2),
    .hBarSel_0_2_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_0_2_ap_vld),
    .xBar_V_1(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_xBar_V_1),
    .xBar_V_1_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_xBar_V_1_ap_vld),
    .s(s),
    .zonePlateVAddr(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_zonePlateVAddr),
    .zonePlateVAddr_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_zonePlateVAddr_ap_vld),
    .zonePlateVDelta(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_zonePlateVDelta),
    .zonePlateVDelta_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_zonePlateVDelta_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln518_fu_771_p2 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_ap_start_reg <= 1'b1;
        end else if ((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_ap_ready == 1'b1)) begin
            grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        hBarSel_0_4_loc_0_fu_294 <= hBarSel_0_2;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_0_4_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        hBarSel_0_4_loc_0_fu_294 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_0_4_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        hBarSel_1_4_loc_0_fu_282 <= hBarSel_1_2;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_1_4_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        hBarSel_1_4_loc_0_fu_282 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_1_4_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        hdata_flag_0_reg_418 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hdata_flag_1_out;
    end else if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        hdata_flag_0_reg_418 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        hdata_loc_0_fu_266 <= hdata;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hdata_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        hdata_loc_0_fu_266 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hdata_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        rampVal_2_flag_0_reg_430 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_2_flag_1_out;
    end else if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        rampVal_2_flag_0_reg_430 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        rampVal_2_loc_0_fu_258 <= rampVal_2;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_2_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        rampVal_2_loc_0_fu_258 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_2_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        rampVal_3_flag_0_reg_406 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_3_flag_1_out;
    end else if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        rampVal_3_flag_0_reg_406 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        rampVal_3_loc_0_fu_302 <= rampVal_1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_3_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        rampVal_3_loc_0_fu_302 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_3_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        rampVal_loc_0_fu_298 <= zext_ln1212_fu_665_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        rampVal_loc_0_fu_298 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        xBar_V_1_loc_0_fu_290 <= xBar_V_1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_lhs_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        xBar_V_1_loc_0_fu_290 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_lhs_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        xBar_V_loc_0_fu_286 <= xBar_V;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_lhs_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        xBar_V_loc_0_fu_286 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_lhs_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        y_fu_206 <= 16'd0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln518_fu_771_p2 == 1'd0))) begin
        y_fu_206 <= y_4_fu_776_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        zonePlateVAddr_loc_0_fu_278 <= zonePlateVAddr;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_zonePlateVAddr_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        zonePlateVAddr_loc_0_fu_278 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_zonePlateVAddr_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        zonePlateVDelta_loc_0_fu_274 <= zonePlateVDelta;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_zonePlateVDelta_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        zonePlateVDelta_loc_0_fu_274 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_zonePlateVDelta_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln1488_reg_1244 <= add_ln1488_fu_874_p2;
        cmp11_i_reg_1239 <= cmp11_i_fu_859_p2;
        icmp_ln1592_1_reg_1254 <= icmp_ln1592_1_fu_886_p2;
        icmp_ln1592_2_reg_1264 <= icmp_ln1592_2_fu_900_p2;
        icmp_ln1592_reg_1249 <= icmp_ln1592_fu_879_p2;
        or_ln1592_reg_1259 <= or_ln1592_fu_893_p2;
        rev102_reg_1234 <= rev102_fu_853_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln518_fu_771_p2 == 1'd0))) begin
        cmp35_not_reg_1224 <= cmp35_not_fu_800_p2;
        outpix_val_V_1_load_reg_1199 <= outpix_val_V_1_fu_238;
        outpix_val_V_2_load_reg_1204 <= outpix_val_V_2_fu_242;
        outpix_val_V_3_load_reg_1209 <= outpix_val_V_3_fu_246;
        outpix_val_V_4_load_reg_1214 <= outpix_val_V_4_fu_250;
        outpix_val_V_5_load_reg_1219 <= outpix_val_V_5_fu_254;
        outpix_val_V_load_reg_1194 <= outpix_val_V_fu_234;
        ult_reg_1229 <= ult_fu_805_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_0_2_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        hBarSel_0_2 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_0_2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_1_2_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        hBarSel_1_2 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hBarSel_1_2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_hdata_flag_0_phi_fu_422_p4 == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln518_fu_771_p2 == 1'd1))) begin
        hdata <= hdata_new_0_fu_270;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hdata_new_1_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        hdata_new_0_fu_270 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_hdata_new_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_outpix_val_V_7_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        outpix_val_V_1_fu_238 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_outpix_val_V_7_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_outpix_val_V_8_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        outpix_val_V_2_fu_242 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_outpix_val_V_8_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_outpix_val_V_9_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        outpix_val_V_3_fu_246 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_outpix_val_V_9_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_outpix_val_V_10_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        outpix_val_V_4_fu_250 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_outpix_val_V_10_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_outpix_val_V_11_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        outpix_val_V_5_fu_254 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_outpix_val_V_11_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_outpix_val_V_6_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        outpix_val_V_fu_234 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_outpix_val_V_6_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_0_0_0_0242372_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_0_0_0_0242373_lcssa386_fu_210 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_0_0_0_0242372_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_1_0_0_0244374_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_1_0_0_0244375_lcssa389_fu_214 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_1_0_0_0244374_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_2_0_0_0246376_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_2_0_0_0246377_lcssa392_fu_218 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_2_0_0_0246376_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_3_0_0_0248378_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_3_0_0_0248379_lcssa395_fu_222 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_3_0_0_0248378_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_4_0_0_0250380_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_4_0_0_0250381_lcssa398_fu_226 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_4_0_0_0250380_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_5_0_0_0252382_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_5_0_0_0252383_lcssa401_fu_230 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_p_0_5_0_0_0252382_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln518_fu_771_p2 == 1'd1))) begin
        rampStart <= add_ln705_fu_815_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        rampStart_load_reg_1167 <= rampStart;
        shl_ln_reg_1174[15 : 8] <= shl_ln_fu_701_p3[15 : 8];
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        rampVal <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_rampVal_3_flag_0_phi_fu_410_p4 == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln518_fu_771_p2 == 1'd1))) begin
        rampVal_1 <= rampVal_3_new_0_fu_306;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_rampVal_2_flag_0_phi_fu_434_p4 == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln518_fu_771_p2 == 1'd1))) begin
        rampVal_2 <= rampVal_2_new_0_fu_262;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_2_new_1_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        rampVal_2_new_0_fu_262 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_2_new_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_3_new_1_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        rampVal_3_new_0_fu_306 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_rampVal_3_new_1_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        trunc_ln518_reg_1186 <= trunc_ln518_fu_767_p1;
        y_3_reg_1179 <= y_fu_206;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_xBar_V_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        xBar_V <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_xBar_V;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_xBar_V_1_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        xBar_V_1 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_xBar_V_1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_zonePlateVAddr_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        zonePlateVAddr <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_zonePlateVAddr;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_zonePlateVDelta_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        zonePlateVDelta <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_zonePlateVDelta;
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (real_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln518_fu_771_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        bckgndYUV_write = grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_bckgndYUV_write;
    end else begin
        bckgndYUV_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln518_fu_771_p2 == 1'd1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        srcYUV_read = grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_srcYUV_read;
    end else begin
        srcYUV_read = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln518_fu_771_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Sel_fu_865_p4 = {{y_3_reg_1179[7:6]}};

assign add_i_fu_637_p2 = (trunc_ln506_fu_627_p1 + 14'd7);

assign add_ln1488_fu_874_p2 = (rampStart_load_reg_1167 + trunc_ln518_reg_1186);

assign add_ln705_fu_815_p2 = (motionSpeed + rampStart);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

assign ap_phi_mux_hdata_flag_0_phi_fu_422_p4 = hdata_flag_0_reg_418;

assign ap_phi_mux_rampVal_2_flag_0_phi_fu_434_p4 = rampVal_2_flag_0_reg_430;

assign ap_phi_mux_rampVal_3_flag_0_phi_fu_410_p4 = rampVal_3_flag_0_reg_406;

assign ap_ready = internal_ap_ready;

assign bckgndYUV_din = grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_bckgndYUV_din;

assign cmp11_i_fu_859_p2 = ((y_3_reg_1179 != 16'd0) ? 1'b1 : 1'b0);

assign cmp35_not_fu_800_p2 = ((y_fu_206 < passthruStartY) ? 1'b1 : 1'b0);

assign grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_ap_start = grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_ap_start_reg;

assign grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_barWidth = {{add_i_fu_637_p2[13:3]}};

assign grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_barWidth_cast = {{add_i_fu_637_p2[13:3]}};

assign grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_cmp6 = ((enableInput != 8'd0) ? 1'b1 : 1'b0);

assign grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_442_trunc_ln = height[13:0];

assign icmp_ln1592_1_fu_886_p2 = ((Sel_fu_865_p4 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln1592_2_fu_900_p2 = ((Sel_fu_865_p4 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln1592_fu_879_p2 = ((Sel_fu_865_p4 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln518_fu_771_p2 = ((y_fu_206 == height) ? 1'b1 : 1'b0);

assign or_ln1592_fu_893_p2 = (icmp_ln1592_fu_879_p2 | icmp_ln1592_1_fu_886_p2);

assign rev102_fu_853_p2 = (ult_reg_1229 ^ 1'd1);

assign shl_ln_fu_701_p3 = {{rampStart}, {8'd0}};

assign start_out = real_start;

assign trunc_ln506_fu_627_p1 = width[13:0];

assign trunc_ln518_fu_767_p1 = y_fu_206[7:0];

assign ult_fu_805_p2 = ((y_fu_206 < passthruEndY) ? 1'b1 : 1'b0);

assign y_4_fu_776_p2 = (y_fu_206 + 16'd1);

assign zext_ln1212_fu_665_p1 = rampVal;

always @ (posedge ap_clk) begin
    shl_ln_reg_1174[7:0] <= 8'b00000000;
end

endmodule //design_1_v_tpg_0_0_tpgBackground
